import { Assignment, AttendanceRecord, ClassRoom, Student, SubmissionRecord } from "./attendance-assignment";
export class AttendanceStoreError extends Error{constructor(){super("데이터를 저장하지 못했습니다. 입력 내용은 화면에 유지됩니다. 잠시 후 다시 시도해 주세요.");this.name="AttendanceStoreError";}}
const config=()=>{const url=process.env.SUPABASE_URL,key=process.env.SUPABASE_PUBLISHABLE_KEY,secret=process.env.SUPABASE_OWNER_SECRET;if(!url||!key||!secret||secret.length<32)throw new AttendanceStoreError();return{url,key,secret};};
async function ownerKey(email:string,secret:string){const e=new TextEncoder(),key=await crypto.subtle.importKey("raw",e.encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]),signed=await crypto.subtle.sign("HMAC",key,e.encode(email.trim().toLowerCase()));return Array.from(new Uint8Array(signed),b=>b.toString(16).padStart(2,"0")).join("");}
export async function attendanceStoreAuth(email:string){const {url,key,secret}=config();return{url,key,owner:await ownerKey(email,secret)};}
export async function attendanceStoreRequest(email:string,table:string,path="",init:RequestInit={}){const {url,key,owner}=await attendanceStoreAuth(email);const response=await fetch(`${url}/rest/v1/${table}${path}`,{...init,headers:{apikey:key,"x-owner-key":owner,"Content-Type":"application/json",...(init.headers||{})},cache:"no-store"});if(!response.ok)throw new AttendanceStoreError();return response;}
const auth=attendanceStoreAuth,request=attendanceStoreRequest;
const baseHeaders={Prefer:"return=representation"};
export async function loadTracker(email:string){
 const [classes,students,attendance,assignments,submissions]=await Promise.all([
  request(email,"teacher_classes","?select=id,school_year,grade,class_number,name&order=created_at"),request(email,"class_students","?select=id,class_id,student_number,display_name,is_active&order=student_number"),request(email,"attendance_records","?select=id,class_id,student_id,attendance_date,status,note"),request(email,"class_assignments","?select=id,class_id,title,subject,description,assigned_date,due_date,status&order=due_date.desc"),request(email,"submission_records","?select=id,assignment_id,student_id,status,note")]);
 const cr=await classes.json() as Record<string,unknown>[],sr=await students.json() as Record<string,unknown>[],ar=await attendance.json() as Record<string,unknown>[],asr=await assignments.json() as Record<string,unknown>[],sub=await submissions.json() as Record<string,unknown>[];
 return{classes:cr.map(r=>({id:r.id,schoolYear:r.school_year,grade:r.grade,classNumber:r.class_number,name:r.name||undefined})) as ClassRoom[],students:sr.map(r=>({id:r.id,classId:r.class_id,studentNumber:r.student_number,displayName:r.display_name,isActive:r.is_active})) as Student[],attendance:ar.map(r=>({id:r.id,classId:r.class_id,studentId:r.student_id,attendanceDate:r.attendance_date,status:r.status,note:r.note||""})) as AttendanceRecord[],assignments:asr.map(r=>({id:r.id,classId:r.class_id,title:r.title,subject:r.subject||"",description:r.description||"",assignedDate:r.assigned_date||"",dueDate:r.due_date,status:r.status})) as Assignment[],submissions:sub.map(r=>({id:r.id,assignmentId:r.assignment_id,studentId:r.student_id,status:r.status,note:r.note||""})) as SubmissionRecord[]};
}
export async function createClass(email:string,input:Omit<ClassRoom,"id">){const {owner}=await auth(email);const response=await request(email,"teacher_classes","",{method:"POST",headers:baseHeaders,body:JSON.stringify({owner_key:owner,school_year:input.schoolYear,grade:input.grade,class_number:input.classNumber,name:input.name||null})});const [r]=await response.json() as {id:string}[];return{...input,id:r.id};}
export async function deleteClass(email:string,classId:string){
 if(!classId)throw new AttendanceStoreError();
 await request(email,"teacher_classes",`?id=eq.${encodeURIComponent(classId)}`,{method:"DELETE",headers:{Prefer:"return=minimal"}});
}
export async function saveStudent(email:string,input:Omit<Student,"id">&{id?:string}){const {owner}=await auth(email),body={owner_key:owner,class_id:input.classId,student_number:input.studentNumber,display_name:input.displayName,is_active:input.isActive};const response=await request(email,"class_students",input.id?`?id=eq.${input.id}`:"",{method:input.id?"PATCH":"POST",headers:baseHeaders,body:JSON.stringify(body)});const [r]=await response.json() as {id:string}[];return{...input,id:r.id};}
export async function saveAttendance(email:string,records:AttendanceRecord[]){const {owner}=await auth(email);await request(email,"attendance_records","?on_conflict=class_id,student_id,attendance_date",{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify(records.map(r=>({owner_key:owner,class_id:r.classId,student_id:r.studentId,attendance_date:r.attendanceDate,status:r.status,note:r.note||null,updated_at:new Date().toISOString()})))});}
export async function saveAssignment(email:string,input:Omit<Assignment,"id">&{id?:string}){const {owner}=await auth(email),body={owner_key:owner,class_id:input.classId,title:input.title,subject:input.subject||null,description:input.description||null,assigned_date:input.assignedDate||null,due_date:input.dueDate,status:input.status};const response=await request(email,"class_assignments",input.id?`?id=eq.${input.id}`:"",{method:input.id?"PATCH":"POST",headers:baseHeaders,body:JSON.stringify(body)});const [r]=await response.json() as {id:string}[];return{...input,id:r.id};}
export async function saveSubmissions(email:string,records:SubmissionRecord[]){const {owner}=await auth(email);await request(email,"submission_records","?on_conflict=assignment_id,student_id",{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify(records.map(r=>({owner_key:owner,assignment_id:r.assignmentId,student_id:r.studentId,status:r.status,note:r.note||null,updated_at:new Date().toISOString()})))});}
