import { ENGLISH_PROBLEM_TYPES, problemTypeLabel, type EnglishLevel, type EnglishProblemType } from "./daily-english-config.ts";
export type VocabularyItem={id:string;word:string;meaning:string;partOfSpeech?:string;exampleSentence?:string;sentenceMeaning?:string};
export type SentenceItem={id:string;sentence:string;meaning:string;keyExpression?:string};
export type EnglishContent={vocabulary:VocabularyItem[];sentences:SentenceItem[]};
export type EnglishProblem={id:string;type:EnglishProblemType;instruction:string;prompt:string;options:string[];correctAnswer:string;explanation?:string;sourceItemId:string;metadata:Record<string,string|number|boolean>};
export type EnglishWorksheetSettings={grade:string;semester:"1"|"2"|"none";level:EnglishLevel;topic:string;typeCounts:Partial<Record<EnglishProblemType,number>>;total:10|15|20|30;columns:1|2;showNumbers:boolean;spacing:"narrow"|"normal"|"wide";customTitle?:string};
export type EnglishWorksheet={id:string;seed:string;createdAt:string;title:string;settings:EnglishWorksheetSettings;problems:EnglishProblem[]};
export class EnglishWorksheetError extends Error{}
const clean=(v:unknown,max=300)=>typeof v==="string"?v.trim().slice(0,max):"";
const key=(v:string)=>v.trim().toLocaleLowerCase();
export function parseVocabularyLines(text:string){const items:VocabularyItem[]=[],errors:Array<{line:number;message:string}>=[];text.split(/\r?\n/).forEach((line,i)=>{if(!line.trim())return;const parts=line.split("|").map(x=>x.trim());if(parts.length<2||!parts[0]||!parts[1])errors.push({line:i+1,message:"영어 단어와 한국어 뜻을 | 로 구분해 주세요."});else items.push({id:`manual-${i}-${key(parts[0])}`,word:parts[0],meaning:parts[1],partOfSpeech:parts[2]||undefined,exampleSentence:parts[3]||undefined,sentenceMeaning:parts[4]||undefined});});return{items:dedupeVocabulary(items),errors};}
export function dedupeVocabulary(items:VocabularyItem[]){const seen=new Set<string>();return items.filter(x=>{const k=key(x.word);if(!k||!x.meaning.trim()||seen.has(k))return false;seen.add(k);return true;});}
export function dedupeSentences(items:SentenceItem[]){const seen=new Set<string>();return items.filter(x=>{const k=key(x.sentence).replace(/[.!?]+$/,'');if(!k||!x.meaning.trim()||seen.has(k))return false;seen.add(k);return true;});}
const hash=(s:string)=>{let h=2166136261;for(const c of s){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0};
const rng=(seed:string)=>{let a=hash(seed);return()=>{a+=0x6D2B79F5;let t=a;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}};
const shuffle=<T>(arr:T[],r:()=>number)=>{const out=[...arr];for(let i=out.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[out[i],out[j]]=[out[j],out[i]]}return out};
const distractors=(correct:string,pool:string[],r:()=>number,count=3)=>shuffle([...new Set(pool.filter(x=>key(x)!==key(correct)))],r).slice(0,count);
function makeProblem(type:EnglishProblemType,index:number,content:EnglishContent,r:()=>number):EnglishProblem|null{
 const words=content.vocabulary,sentences=content.sentences,w=words[index%words.length],s=sentences[index%sentences.length];let prompt="",answer="",options:string[]=[],explanation="",source="";
 if(type.startsWith("reading-")){if(sentences.length<2)return null;const passage=sentences.slice(0,Math.min(4,sentences.length)).map(x=>x.sentence).join(" ");const target=sentences[index%sentences.length];prompt=`${passage}\n\n${type==="reading-short"?"글에서 확인할 수 있는 문장 하나를 쓰세요.":"글의 내용과 맞는 것을 고르세요."}`;answer=target.sentence;options=type==="reading-short"?[]:shuffle([answer,...distractors(answer,sentences.map(x=>x.sentence),r,3)],r);explanation=`근거: ${target.sentence}`;source=target.id;}
 else if(type.startsWith("sentence-")||type==="choose-sentence"){if(!s)return null;source=s.id;answer=s.sentence;explanation=s.meaning;if(type==="sentence-order"){prompt=shuffle(s.sentence.replace(/[.!?]+$/,'').toLowerCase().split(/\s+/),r).join(" / ");}
 else if(type==="sentence-blank"){const tokens=s.sentence.split(/\s+/);const at=Math.max(0,Math.min(tokens.length-1,Math.floor(r()*tokens.length)));answer=tokens[at].replace(/[.,!?]/g,"");prompt=tokens.map((x,i)=>i===at?"_____":x).join(" ");options=shuffle([answer,...distractors(answer,words.map(x=>x.word),r,3)],r);}
 else if(type==="sentence-match"||type==="choose-sentence"){prompt=s.meaning;options=shuffle([s.sentence,...distractors(s.sentence,sentences.map(x=>x.sentence),r,3)],r);}
 else if(type==="sentence-meaning"){prompt=s.sentence;answer=s.meaning;}else{prompt=s.meaning;}}
 else {if(!w)return null;source=w.id;answer=w.word;explanation=w.meaning;if(type==="word-match"||type==="choose-word"){prompt=type==="word-match"?w.word:w.meaning;answer=type==="word-match"?w.meaning:w.word;const pool=type==="word-match"?words.map(x=>x.meaning):words.map(x=>x.word);options=shuffle([answer,...distractors(answer,pool,r,3)],r);}
 else if(type==="meaning-write"){prompt=w.word;answer=w.meaning;}else if(type==="word-write"){prompt=w.meaning;}
 else if(type==="missing-letters"){const chars=[...w.word];const positions=shuffle(chars.map((_,i)=>i).filter(i=>/[a-z]/i.test(chars[i])),r).slice(0,Math.max(1,Math.min(2,Math.floor(chars.length/3))));prompt=chars.map((c,i)=>positions.includes(i)?"_":c).join("");}
 else if(type==="scramble-word"){let mixed=shuffle([...w.word],r).join("");if(mixed===w.word)mixed=[...w.word].reverse().join("");prompt=mixed;}}
 return{id:`p-${index}-${type}`,type,instruction:problemTypeLabel(type),prompt,options,correctAnswer:answer,explanation,sourceItemId:source,metadata:{}};
}
export function createEnglishWorksheet(settings:EnglishWorksheetSettings,content:EnglishContent,seed:string,createdAt=new Date().toISOString()):EnglishWorksheet{
 const sum=Object.values(settings.typeCounts).reduce((a,b)=>a+(b||0),0);if(sum!==settings.total)throw new EnglishWorksheetError(`유형별 문제 수가 전체보다 ${Math.abs(settings.total-sum)}문제 ${sum<settings.total?"부족":"초과"}합니다.`);
 const selected=Object.entries(settings.typeCounts).filter((x):x is [EnglishProblemType,number]=>!!x[1]);if(!selected.length)throw new EnglishWorksheetError("문제 유형을 한 개 이상 선택해 주세요.");
 if(!content.vocabulary.length&&!content.sentences.length)throw new EnglishWorksheetError("확인된 학습 단어 또는 문장을 준비해 주세요.");
 const r=rng(`${seed}:${JSON.stringify(settings)}:${JSON.stringify(content)}`),problems:EnglishProblem[]=[];
 for(const [type,count] of selected){const group=ENGLISH_PROBLEM_TYPES.find(x=>x[0]===type)?.[2];const available=group==="word"?content.vocabulary.length:content.sentences.length;if(!available)throw new EnglishWorksheetError(`${problemTypeLabel(type)}에 필요한 ${group==="word"?"단어":"문장"}가 없습니다.`);if(count>available*2)throw new EnglishWorksheetError(`${problemTypeLabel(type)} ${count}문제를 만들려면 학습 내용을 더 추가해 주세요.`);for(let i=0;i<count;i++){const p=makeProblem(type,i+problems.length,{vocabulary:shuffle(content.vocabulary,r),sentences:shuffle(content.sentences,r)},r);if(!p)throw new EnglishWorksheetError("선택한 문제 유형에 필요한 학습 내용이 부족합니다.");problems.push(p)}}
 const ordered=shuffle(problems,r).map((p,i)=>({...p,id:`${seed}-${i+1}`}));return{id:`EN-${hash(seed).toString(36).toUpperCase()}`,seed,createdAt,title:settings.customTitle?.trim()||`일일영어 · ${settings.topic}`,settings,problems:ordered};
}
export const createEnglishSeed=()=>`${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`;
const obj=(v:unknown):v is Record<string,unknown>=>!!v&&typeof v==="object"&&!Array.isArray(v);
export function validateEnglishRecommendation(v:unknown):EnglishContent|null{if(!obj(v)||!Array.isArray(v.vocabulary)||!Array.isArray(v.sentences))return null;const vocabulary:VocabularyItem[]=[];for(let i=0;i<v.vocabulary.length;i++){const x=v.vocabulary[i];if(!obj(x)||!clean(x.word)||!clean(x.meaning))return null;vocabulary.push({id:`ai-v-${i}`,word:clean(x.word),meaning:clean(x.meaning),partOfSpeech:clean(x.partOfSpeech)||undefined,exampleSentence:clean(x.exampleSentence)||undefined,sentenceMeaning:clean(x.sentenceMeaning)||undefined})}const sentences:SentenceItem[]=[];for(let i=0;i<v.sentences.length;i++){const x=v.sentences[i];if(!obj(x)||!clean(x.sentence)||!clean(x.meaning))return null;sentences.push({id:`ai-s-${i}`,sentence:clean(x.sentence),meaning:clean(x.meaning),keyExpression:clean(x.keyExpression)||undefined})}return{vocabulary:dedupeVocabulary(vocabulary),sentences:dedupeSentences(sentences)}}
export const englishRecommendationSchema={type:"object",additionalProperties:false,properties:{vocabulary:{type:"array",items:{type:"object",additionalProperties:false,properties:{word:{type:"string"},meaning:{type:"string"},partOfSpeech:{type:"string"},exampleSentence:{type:"string"},sentenceMeaning:{type:"string"}},required:["word","meaning","partOfSpeech","exampleSentence","sentenceMeaning"]}},sentences:{type:"array",items:{type:"object",additionalProperties:false,properties:{sentence:{type:"string"},meaning:{type:"string"},keyExpression:{type:"string"}},required:["sentence","meaning","keyExpression"]}}},required:["vocabulary","sentences"]};
export function buildEnglishRecommendationPrompt(input:{grade:string;semester:string;level:EnglishLevel;topic:string;wordCount:number;sentenceCount:number;request?:string}){return `초등 영어 학습지에 사용할 검토용 학습 내용을 JSON 구조로 추천하세요. 학년: ${input.grade}, 학기: ${input.semester}, 수준: ${input.level}, 생활 주제: ${input.topic}, 단어 ${input.wordCount}개, 문장 ${input.sentenceCount}개. 추가 요청: ${input.request||"없음"}. 특정 교과서·단원·성취기준을 만들거나 복제하지 말고 일상적이며 문법적으로 자연스럽고 학생에게 안전한 표현만 사용하세요. 중복, 전문용어, 고정관념을 피하세요. 한국어 뜻은 예문 문맥에 맞추고 내부 설명은 반환하지 마세요.`}
