import { FIRST_GRADE_KOREAN_LESSON_REFERENCE, LESSON_TYPES, type LessonType } from "./lesson-plan-reference.ts";

export const STUDENT_LEVELS = ["기초", "보통", "심화", "수준 혼합"] as const;
export const LESSON_STAGES = ["도입", "전개", "정리"] as const;
export const SEMESTERS = ["1학기", "2학기", "학기 구분 없이"] as const;

export type LessonPlanInput = {
  grade:"1학년"; subject:"국어"; semester:(typeof SEMESTERS)[number]; unit:string; topic:string; achievementStandard:string;
  currentSession:number; totalSessions:number; durationMinutes:number; studentLevel:(typeof STUDENT_LEVELS)[number]; lessonType:LessonType;
  textbookName?:string; textbookPages?:string; coreContent?:string; classCharacteristics?:string; desiredActivities?:string; availableMaterials?:string; additionalRequests?:string;
};
export type LessonPlanErrors = Partial<Record<keyof LessonPlanInput,string>>;
export type LessonStage = {stage:(typeof LESSON_STAGES)[number];learningContent:string;minutes:number;teacherActivities:string[];studentActivities:string[];materialsAndNotes:string[]};
export type LessonPlanData = {
  title:string;lessonType:string;learningObjectives:string[];teacherMaterials:string[];studentMaterials:string[];lessonStages:LessonStage[];
  assessment:{content:string[];method:string[];observableBehaviors:string[];criteria:{high:string;medium:string;low:string};alignmentEvidence:string};
  levelSupport:Array<{level:"기초"|"보통"|"심화";support:string[]}>;
};

const includes=<T extends string>(a:readonly T[],v:unknown):v is T=>typeof v==="string"&&a.includes(v as T);
const clean=(v:unknown,max=2000)=>typeof v==="string"?v.trim().slice(0,max):"";
const obj=(v:unknown):v is Record<string,unknown>=>!!v&&typeof v==="object"&&!Array.isArray(v);
const positive=(v:unknown)=>typeof v==="number"&&Number.isInteger(v)&&v>0;
const strings=(v:unknown):v is string[]=>Array.isArray(v)&&v.length>0&&v.every(x=>typeof x==="string"&&x.trim());

export function validateLessonPlanInput(value:unknown):{data?:LessonPlanInput;errors:LessonPlanErrors}{
  if(!obj(value))return{errors:{topic:"수업 정보를 확인해 주세요."}};const errors:LessonPlanErrors={};
  if(!includes(SEMESTERS,value.semester))errors.semester="학기를 선택해 주세요.";if(!clean(value.unit,300))errors.unit="단원명을 입력해 주세요.";if(!clean(value.topic,500))errors.topic="차시 주제를 입력해 주세요.";if(!clean(value.achievementStandard,1200))errors.achievementStandard="성취기준을 입력해 주세요.";
  if(!positive(value.currentSession))errors.currentSession="현재 차시는 1 이상의 정수로 입력해 주세요.";if(!positive(value.totalSessions))errors.totalSessions="전체 차시는 1 이상의 정수로 입력해 주세요.";if(positive(value.currentSession)&&positive(value.totalSessions)&&Number(value.currentSession)>Number(value.totalSessions))errors.currentSession="현재 차시는 전체 차시보다 클 수 없어요.";
  if(!positive(value.durationMinutes))errors.durationMinutes="수업 시간은 1분 이상의 정수로 입력해 주세요.";if(!includes(STUDENT_LEVELS,value.studentLevel))errors.studentLevel="학생 수준을 선택해 주세요.";if(!includes(LESSON_TYPES,value.lessonType))errors.lessonType="수업 유형을 선택해 주세요.";
  if(Object.keys(errors).length)return{errors};const optional=(k:keyof LessonPlanInput,max=2000)=>clean(value[k],max)||undefined;return{errors,data:{grade:"1학년",subject:"국어",semester:value.semester as LessonPlanInput["semester"],unit:clean(value.unit,300),topic:clean(value.topic,500),achievementStandard:clean(value.achievementStandard,1200),currentSession:Number(value.currentSession),totalSessions:Number(value.totalSessions),durationMinutes:Number(value.durationMinutes),studentLevel:value.studentLevel as LessonPlanInput["studentLevel"],lessonType:value.lessonType as LessonType,textbookName:optional("textbookName",200),textbookPages:optional("textbookPages",100),coreContent:optional("coreContent"),classCharacteristics:optional("classCharacteristics"),desiredActivities:optional("desiredActivities"),availableMaterials:optional("availableMaterials"),additionalRequests:optional("additionalRequests")}};
}

export function validateLessonPlanOutput(value:unknown,input:LessonPlanInput):LessonPlanData|null{
  if(!obj(value)||typeof value.title!=="string"||typeof value.lessonType!=="string"||!strings(value.learningObjectives)||value.learningObjectives.length>2||!strings(value.teacherMaterials)||!strings(value.studentMaterials)||!Array.isArray(value.lessonStages)||value.lessonStages.length!==3)return null;
  const stages:LessonStage[]=[];for(let i=0;i<3;i++){const s=value.lessonStages[i];if(!obj(s)||s.stage!==LESSON_STAGES[i]||typeof s.learningContent!=="string"||!s.learningContent.trim()||!positive(s.minutes)||!strings(s.teacherActivities)||!strings(s.studentActivities)||!strings(s.materialsAndNotes))return null;if(!(s.teacherActivities as string[]).every(x=>/^[▣○•]/.test(x))||!(s.studentActivities as string[]).every(x=>/^[-]/.test(x))||!(s.materialsAndNotes as string[]).every(x=>/^[▶※]/.test(x)))return null;stages.push(s as LessonStage)}if(stages.reduce((a,b)=>a+b.minutes,0)!==input.durationMinutes)return null;
  if(!obj(value.assessment))return null;const a=value.assessment;if(!strings(a.content)||!strings(a.method)||!strings(a.observableBehaviors)||!obj(a.criteria)||typeof a.criteria.high!=="string"||typeof a.criteria.medium!=="string"||typeof a.criteria.low!=="string"||typeof a.alignmentEvidence!=="string"||!a.alignmentEvidence.trim())return null;const criteria=[a.criteria.high,a.criteria.medium,a.criteria.low].join(" ");if(/(매우 우수|대체로 잘|부족함|열심히|태도가 좋|못한다)/.test(criteria))return null;
  if(!Array.isArray(value.levelSupport)||!value.levelSupport.length)return null;const expected=input.studentLevel==="수준 혼합"?["기초","보통","심화"]:[input.studentLevel];const support:LessonPlanData["levelSupport"]=[];for(const item of value.levelSupport){if(!obj(item)||!expected.includes(item.level as never)||!strings(item.support))return null;support.push(item as LessonPlanData["levelSupport"][number])}if(new Set(support.map(x=>x.level)).size!==expected.length)return null;
  return{title:value.title.trim(),lessonType:value.lessonType,learningObjectives:value.learningObjectives,teacherMaterials:value.teacherMaterials,studentMaterials:value.studentMaterials,lessonStages:stages,assessment:a as LessonPlanData["assessment"],levelSupport:support};
}

const prefix=(value:unknown,mark:string)=>typeof value==="string"&&value.trim()?(/^[▣○•▶※-]/.test(value.trim())?value.trim():`${mark} ${value.trim()}`):value;
export function normalizeLessonPlanOutput(value:unknown,input:LessonPlanInput):unknown{
  if(!obj(value)||!Array.isArray(value.lessonStages))return value;
  const rawMinutes=value.lessonStages.map(x=>obj(x)&&positive(x.minutes)?Number(x.minutes):0);const total=rawMinutes.reduce((a,b)=>a+b,0);
  let minutes=rawMinutes;if(total!==input.durationMinutes){const intro=Math.max(1,Math.round(input.durationMinutes*.125));const closing=Math.max(1,Math.round(input.durationMinutes*.125));minutes=[intro,Math.max(1,input.durationMinutes-intro-closing),Math.max(1,input.durationMinutes-intro-Math.max(1,input.durationMinutes-intro-closing))];}
  return{...value,lessonStages:value.lessonStages.map((stage,i)=>obj(stage)?{...stage,stage:LESSON_STAGES[i]||stage.stage,minutes:minutes[i],teacherActivities:Array.isArray(stage.teacherActivities)?stage.teacherActivities.map((x,n)=>prefix(x,n===0?"▣":"○")):stage.teacherActivities,studentActivities:Array.isArray(stage.studentActivities)?stage.studentActivities.map(x=>prefix(x,"-")):stage.studentActivities,materialsAndNotes:Array.isArray(stage.materialsAndNotes)?stage.materialsAndNotes.map(x=>prefix(x,"※")):stage.materialsAndNotes}:stage)};
}

const sa={type:"array",items:{type:"string"},minItems:1};
export const lessonPlanJsonSchema:Record<string,unknown>={type:"object",additionalProperties:false,properties:{title:{type:"string"},lessonType:{type:"string"},learningObjectives:{type:"array",items:{type:"string"},minItems:1,maxItems:2},teacherMaterials:sa,studentMaterials:sa,lessonStages:{type:"array",minItems:3,maxItems:3,items:{type:"object",additionalProperties:false,properties:{stage:{type:"string",enum:LESSON_STAGES},learningContent:{type:"string"},minutes:{type:"integer",minimum:1},teacherActivities:sa,studentActivities:sa,materialsAndNotes:sa},required:["stage","learningContent","minutes","teacherActivities","studentActivities","materialsAndNotes"]}},assessment:{type:"object",additionalProperties:false,properties:{content:sa,method:sa,observableBehaviors:sa,criteria:{type:"object",additionalProperties:false,properties:{high:{type:"string"},medium:{type:"string"},low:{type:"string"}},required:["high","medium","low"]},alignmentEvidence:{type:"string"}},required:["content","method","observableBehaviors","criteria","alignmentEvidence"]},levelSupport:{type:"array",minItems:1,maxItems:3,items:{type:"object",additionalProperties:false,properties:{level:{type:"string",enum:["기초","보통","심화"]},support:sa},required:["level","support"]}}},required:["title","lessonType","learningObjectives","teacherMaterials","studentMaterials","lessonStages","assessment","levelSupport"]};

export type LessonPlanOverview={grade:string;subject:string;semester:string;unit:string;topic:string;session:string;textbook:string;achievementStandard:string};
export function formatLessonPlanText(result:LessonPlanData&{overview:LessonPlanOverview}):string{
  return [result.title,`교과: ${result.overview.subject}`,`학년: ${result.overview.grade}`,`학기: ${result.overview.semester}`,`단원: ${result.overview.unit}`,`차시 주제: ${result.overview.topic}`,`차시: ${result.overview.session}`,`교과서: ${result.overview.textbook}`,`수업 유형: ${result.lessonType}`,`성취기준: ${result.overview.achievementStandard}`,"\n[학습 목표]",...result.learningObjectives.map(x=>`- ${x}`),"\n[준비물]","교사: "+result.teacherMaterials.join(", "),"학생: "+result.studentMaterials.join(", "),"\n[수업 흐름]",...result.lessonStages.flatMap(s=>[`${s.stage} · ${s.learningContent} (${s.minutes}분)`,`교사 활동: ${s.teacherActivities.join(" / ")}`,`학생 활동: ${s.studentActivities.join(" / ")}`,`자료 및 유의점: ${s.materialsAndNotes.join(" / ")}`]),"\n[평가 계획]","평가 내용: "+result.assessment.content.join(" / "),"평가 방법: "+result.assessment.method.join(" / "),"관찰 행동: "+result.assessment.observableBehaviors.join(" / "),`상: ${result.assessment.criteria.high}`,`중: ${result.assessment.criteria.medium}`,`하: ${result.assessment.criteria.low}`,`목표-활동-평가 연결: ${result.assessment.alignmentEvidence}`,"\n[수준별 지원]",...result.levelSupport.map(x=>`${x.level}: ${x.support.join(" / ")}`)].join("\n");
}

export function buildLessonPlanPrompt(input:LessonPlanInput):string{return `초등학교 1학년 국어과 교수·학습 지도안을 구조화된 형식으로 작성하세요. 다음 참고자료는 형식과 설계 원리만 사용하고 출판사 고유 문장이나 사례를 복제하지 마세요.\n${FIRST_GRADE_KOREAN_LESSON_REFERENCE}\n[사용자 입력 - 최우선 근거]\n학기=${input.semester}\n단원=${input.unit}\n차시 주제=${input.topic}\n성취기준(문구 그대로)=${input.achievementStandard}\n차시=${input.currentSession}/${input.totalSessions}차시\n총 시간=${input.durationMinutes}분\n학생 수준=${input.studentLevel}\n수업 유형=${input.lessonType}\n교과서명=${input.textbookName||"입력 없음"}\n교과서 쪽수=${input.textbookPages||"입력 없음"}\n핵심 내용=${input.coreContent||"입력 없음"}\n학급 특성=${input.classCharacteristics||"입력 없음"}\n포함 활동=${input.desiredActivities||"입력 없음"}\n사용 가능 자료=${input.availableMaterials||"입력 없음"}\n추가 요청=${input.additionalRequests||"입력 없음"}\n[생성·검수 규칙]\n- 학교급·학년·교과는 초등학교 1학년 국어로 고정합니다. 입력 성취기준과 단원명을 바꾸지 마세요.\n- 수업 유형이 자동 선택이면 목표에 맞는 유형을 고르고 lessonType에 선택 이유가 드러나는 짧은 유형명을 씁니다.\n- 도입·전개·정리 3단계로 구성하되 각 단계의 learningContent를 분명히 하고 시간 합계는 정확히 ${input.durationMinutes}분으로 맞춥니다. 대부분의 시간은 학생 수행이 있는 전개에 둡니다.\n- teacherActivities와 studentActivities는 같은 개수와 같은 순서로 대응시킵니다. 교사 활동은 ▣, ○, • 중 하나로 시작하고 학생 활동은 - 로 시작합니다. 실제 발문과 1학년의 예상 반응·수행을 씁니다.\n- materialsAndNotes는 모든 항목을 ▶ 또는 ※로 시작합니다. 자료의 용도, 참여·접근성 지원, 정확성, 안전 유의점을 해당 단계에 구체적으로 연결합니다.\n- 입력하지 않은 교과서 쪽수·지문·작품·영상·정답·특정 사이트를 만들지 마세요. 이미지가 입력되지 않았다면 존재하지 않는 그림을 보라고 하지 마세요.\n- 학습 목표의 수행 동사가 학생 활동과 assessment.content·observableBehaviors에 같은 의미로 이어지게 하고 alignmentEvidence에 연결 근거를 한 문장으로 씁니다.\n- criteria의 high·medium·low는 같은 수행을 정확성·독립성·도움 정도로 구분한 관찰 가능한 행동입니다. 학생의 성격·노력·능력을 단정하지 말고 low에는 지원과 다음 학습 방향을 포함합니다.\n- 1학년에게 짧은 발문, 따라 읽기·쓰기, 말하기·듣기, 카드·놀이 같은 구체적 수행을 사용하되 단순 재미로 끝내지 않습니다. 준비·자료 배부·전환·정리 시간을 포함해 실제 가능한 활동량으로 제한합니다.\n- 수준별 지원은 문제 수만 바꾸지 말고 말로 답하기, 카드 고르기, 따라 읽기, 문장 틀처럼 선택 가능한 보편적 지원으로 씁니다.\n- 수업을 실시한 것처럼 결과를 꾸미지 말고 교사가 검토할 초안으로 작성합니다.`;}
