import type { ObservationMemo } from "./student-observation-organizer";

type ObservationRow={id:string;student_identifier:string;observed_on:string;category:ObservationMemo["category"];situation:string|null;observation_memo:string;teacher_support:string|null;subsequent_change:string|null};
export class ObservationStoreError extends Error{constructor(){super("저장된 관찰 메모를 처리하지 못했습니다. 잠시 후 다시 시도해 주세요.");this.name="ObservationStoreError";}}

const config=()=>{const url=process.env.SUPABASE_URL;const key=process.env.SUPABASE_PUBLISHABLE_KEY;const secret=process.env.SUPABASE_OWNER_SECRET;if(!url||!key||!secret||secret.length<32)throw new ObservationStoreError();return{url,key,secret};};
async function ownerKey(email:string,secret:string){const encoder=new TextEncoder();const key=await crypto.subtle.importKey("raw",encoder.encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]);const signed=await crypto.subtle.sign("HMAC",key,encoder.encode(email.trim().toLowerCase()));return Array.from(new Uint8Array(signed),byte=>byte.toString(16).padStart(2,"0")).join("");}
const toMemo=(row:ObservationRow):ObservationMemo=>({id:row.id,studentIdentifier:row.student_identifier,date:row.observed_on,category:row.category,situation:row.situation||undefined,memo:row.observation_memo,teacherSupport:row.teacher_support||undefined,subsequentChange:row.subsequent_change||undefined});
const toRow=(memo:Omit<ObservationMemo,"id">,owner_key:string)=>({owner_key,student_identifier:memo.studentIdentifier,observed_on:memo.date,category:memo.category,situation:memo.situation||null,observation_memo:memo.memo,teacher_support:memo.teacherSupport||null,subsequent_change:memo.subsequentChange||null,updated_at:new Date().toISOString()});

async function authorizedConfig(email:string){const {url,key,secret}=config();return{url,key,owner:await ownerKey(email,secret)};}
async function request(email:string,path:string,init:RequestInit={}){const {url,key,owner}=await authorizedConfig(email);const response=await fetch(`${url}/rest/v1/student_observation_memos${path}`,{...init,headers:{apikey:key,"x-owner-key":owner,"Content-Type":"application/json",...(init.headers||{})},cache:"no-store"});if(!response.ok)throw new ObservationStoreError();return response;}
export async function listObservationMemos(email:string){const response=await request(email,"?select=id,student_identifier,observed_on,category,situation,observation_memo,teacher_support,subsequent_change&order=observed_on.desc,created_at.desc");return((await response.json()) as ObservationRow[]).map(toMemo);}
export async function createObservationMemo(email:string,memo:Omit<ObservationMemo,"id">){const {url,key,owner}=await authorizedConfig(email);const response=await fetch(`${url}/rest/v1/student_observation_memos`,{method:"POST",headers:{apikey:key,"x-owner-key":owner,"Content-Type":"application/json",Prefer:"return=representation"},body:JSON.stringify(toRow(memo,owner)),cache:"no-store"});if(!response.ok)throw new ObservationStoreError();const rows=await response.json() as ObservationRow[];if(!rows[0])throw new ObservationStoreError();return toMemo(rows[0]);}
export async function updateObservationMemo(email:string,id:string,memo:Omit<ObservationMemo,"id">){const {url,key,owner}=await authorizedConfig(email);const response=await fetch(`${url}/rest/v1/student_observation_memos?id=eq.${encodeURIComponent(id)}`,{method:"PATCH",headers:{apikey:key,"x-owner-key":owner,"Content-Type":"application/json",Prefer:"return=representation"},body:JSON.stringify(toRow(memo,owner)),cache:"no-store"});if(!response.ok)throw new ObservationStoreError();const rows=await response.json() as ObservationRow[];if(!rows[0])throw new ObservationStoreError();return toMemo(rows[0]);}
export async function deleteObservationMemo(email:string,id:string){await request(email,`?id=eq.${encodeURIComponent(id)}`,{method:"DELETE"});}
export async function deleteStudentObservationMemos(email:string,studentIdentifier:string){await request(email,`?student_identifier=eq.${encodeURIComponent(studentIdentifier)}`,{method:"DELETE"});}
