export const WRITING_GRADES=["1학년","2학년","3학년","4학년","5학년","6학년"] as const;
export const WRITING_TYPES=["생활문","일기","독후감","편지글","설명하는 글","주장하는 글","이야기","보고서","기타"] as const;
export const FEEDBACK_AREAS=["내용","구성","표현","맞춤법·띄어쓰기"] as const;
export const FEEDBACK_DETAILS=["간단하게","보통","자세하게"] as const;
export type FeedbackArea=(typeof FEEDBACK_AREAS)[number];
export type WritingFeedbackInput={grade:(typeof WRITING_GRADES)[number];writingType:(typeof WRITING_TYPES)[number];topic?:string;conditions?:string;studentText:string;feedbackAreas:FeedbackArea[];detail:(typeof FEEDBACK_DETAILS)[number]};
export type WritingFeedbackErrors=Partial<Record<keyof WritingFeedbackInput,string>>;
type BasicFeedback={strengths:string[];suggestions:string[]};
export type WritingFeedbackData={overallFeedback:{strengths:string;prioritySuggestion:string};contentFeedback:BasicFeedback&{guidingQuestions:string[]};organizationFeedback:BasicFeedback;expressionFeedback:{strengths:string[];revisions:Array<{original:string;suggestion:string;reason:string}>};spellingFeedback:{corrections:Array<{original:string;corrected:string;reason:string}>};revisionChecklist:string[]};
const includes=<T extends string>(values:readonly T[],value:unknown):value is T=>typeof value==="string"&&values.includes(value as T);const clean=(v:unknown,max=10000)=>typeof v==="string"?v.trim().slice(0,max):"";
export function validateWritingFeedbackInput(value:unknown):{data?:WritingFeedbackInput;errors:WritingFeedbackErrors}{if(!value||typeof value!=="object")return{errors:{studentText:"학생이 쓴 글을 입력해 주세요."}};const raw=value as Record<string,unknown>;const errors:WritingFeedbackErrors={};if(!includes(WRITING_GRADES,raw.grade))errors.grade="학년을 선택해 주세요.";if(!includes(WRITING_TYPES,raw.writingType))errors.writingType="글의 종류를 선택해 주세요.";if(!clean(raw.studentText,10000))errors.studentText="학생이 쓴 글을 입력해 주세요.";const areas=Array.isArray(raw.feedbackAreas)?[...new Set(raw.feedbackAreas.filter(x=>includes(FEEDBACK_AREAS,x)))]:[];if(!areas.length)errors.feedbackAreas="피드백 영역을 한 개 이상 선택해 주세요.";if(!includes(FEEDBACK_DETAILS,raw.detail))errors.detail="피드백 상세도를 선택해 주세요.";if(Object.keys(errors).length)return{errors};return{errors,data:{grade:raw.grade as WritingFeedbackInput["grade"],writingType:raw.writingType as WritingFeedbackInput["writingType"],topic:clean(raw.topic,1000)||undefined,conditions:clean(raw.conditions,2000)||undefined,studentText:clean(raw.studentText,10000),feedbackAreas:areas as FeedbackArea[],detail:raw.detail as WritingFeedbackInput["detail"]}};}
const strings=(v:unknown,min=0):v is string[]=>Array.isArray(v)&&v.length>=min&&v.every(x=>typeof x==="string"&&x.trim().length>0);const obj=(v:unknown):v is Record<string,unknown>=>!!v&&typeof v==="object"&&!Array.isArray(v);
export function validateWritingFeedbackOutput(value:unknown,input:WritingFeedbackInput):WritingFeedbackData|null{if(!obj(value)||!obj(value.overallFeedback)||typeof value.overallFeedback.strengths!=="string"||!value.overallFeedback.strengths.trim()||typeof value.overallFeedback.prioritySuggestion!=="string"||!value.overallFeedback.prioritySuggestion.trim()||!obj(value.contentFeedback)||!obj(value.organizationFeedback)||!obj(value.expressionFeedback)||!obj(value.spellingFeedback)||!strings(value.revisionChecklist,2)||value.revisionChecklist.length>4)return null;const c=value.contentFeedback,o=value.organizationFeedback,e=value.expressionFeedback,s=value.spellingFeedback;if(!strings(c.strengths)||!strings(c.suggestions)||!strings(c.guidingQuestions)||!strings(o.strengths)||!strings(o.suggestions)||!strings(e.strengths)||!Array.isArray(e.revisions)||!Array.isArray(s.corrections))return null;for(const r of e.revisions)if(!obj(r)||typeof r.original!=="string"||typeof r.suggestion!=="string"||typeof r.reason!=="string"||!r.original.trim()||!r.suggestion.trim()||!r.reason.trim())return null;for(const r of s.corrections)if(!obj(r)||typeof r.original!=="string"||typeof r.corrected!=="string"||typeof r.reason!=="string"||!r.original.trim()||!r.corrected.trim()||!r.reason.trim())return null;const selected=(area:FeedbackArea)=>input.feedbackAreas.includes(area);if(selected("내용")?(!c.strengths.length||!c.suggestions.length||!c.guidingQuestions.length):(c.strengths.length||c.suggestions.length||c.guidingQuestions.length))return null;if(selected("구성")?(!o.strengths.length||!o.suggestions.length):(o.strengths.length||o.suggestions.length))return null;if(selected("표현")?!e.strengths.length:(e.strengths.length||e.revisions.length))return null;if(!selected("맞춤법·띄어쓰기")&&s.corrections.length)return null;return value as WritingFeedbackData;}
const stringArray={type:"array",items:{type:"string"}};
export const writingFeedbackJsonSchema:Record<string,unknown>={type:"object",additionalProperties:false,properties:{overallFeedback:{type:"object",additionalProperties:false,properties:{strengths:{type:"string"},prioritySuggestion:{type:"string"}},required:["strengths","prioritySuggestion"]},contentFeedback:{type:"object",additionalProperties:false,properties:{strengths:stringArray,suggestions:stringArray,guidingQuestions:stringArray},required:["strengths","suggestions","guidingQuestions"]},organizationFeedback:{type:"object",additionalProperties:false,properties:{strengths:stringArray,suggestions:stringArray},required:["strengths","suggestions"]},expressionFeedback:{type:"object",additionalProperties:false,properties:{strengths:stringArray,revisions:{type:"array",items:{type:"object",additionalProperties:false,properties:{original:{type:"string"},suggestion:{type:"string"},reason:{type:"string"}},required:["original","suggestion","reason"]}}},required:["strengths","revisions"]},spellingFeedback:{type:"object",additionalProperties:false,properties:{corrections:{type:"array",items:{type:"object",additionalProperties:false,properties:{original:{type:"string"},corrected:{type:"string"},reason:{type:"string"}},required:["original","corrected","reason"]}}},required:["corrections"]},revisionChecklist:{type:"array",items:{type:"string"},minItems:2,maxItems:4}},required:["overallFeedback","contentFeedback","organizationFeedback","expressionFeedback","spellingFeedback","revisionChecklist"]};
export function buildWritingFeedbackPrompt(input:WritingFeedbackInput){return `초등학생이 자신의 글을 직접 고칠 수 있도록 구조화된 피드백 초안을 작성하세요.\n[입력]\n- 학년: ${input.grade}\n- 글의 종류: ${input.writingType}\n- 주제 또는 과제: ${input.topic||"입력되지 않음"}\n- 글쓰기 조건: ${input.conditions||"입력되지 않음"}\n- 선택 영역: ${input.feedbackAreas.join(", ")}\n- 상세도: ${input.detail}\n- 학생 원문:\n${input.studentText}\n[원칙]\n- 학생 원문에 근거하고 없는 경험·생각·사건을 만들지 마세요. 학생 대신 글 전체를 다시 쓰지 마세요.\n- ${input.grade} 학생이 이해할 어휘와 문장 길이로, 구체적인 잘한 점을 먼저 쓰세요. 평가·낙인·점수·등급·학생 비교를 하지 마세요.\n- 성격, 지능, 가정환경, 심리 상태를 추측하지 마세요. 개인정보나 다른 학생 이름을 결과에서 불필요하게 반복하지 마세요.\n- 내용이 부족하면 정답을 써 주지 말고 스스로 떠올릴 질문을 제시하세요. 수정 예시는 필요한 문장·표현만 다루고 학생의 목소리와 의도를 유지하세요.\n- 내용은 주제, 필요한 내용, 근거와 예시를 중심으로, 구성은 시작·가운데·끝, 문단, 순서와 연결을 중심으로 피드백하세요.\n- 표현은 자연스러움, 구체적 어휘, 반복, 문장 연결을 중심으로 하세요. 맞춤법·띄어쓰기는 실제 오류만 제시하고 문맥상 맞을 수 있으면 단정하지 마세요. 이유는 쉬운 말로 쓰세요.\n- 선택하지 않은 영역의 모든 배열은 빈 배열로 반환하세요. 맞춤법 오류가 없으면 corrections를 빈 배열로 반환하세요.\n- 간단하게는 영역별 핵심 1개, 보통은 2~3개, 자세하게는 충분한 설명과 필요한 짧은 예시를 제공하세요.\n- revisionChecklist는 학생이 직접 확인할 짧은 항목 2~4개입니다. 교사의 최종 평가가 아니라 수정 조언으로 작성하세요.`;}
