/* eslint-disable react-hooks/set-state-in-effect, @next/next/no-html-link-for-pages */
"use client";
import {useEffect,useMemo,useState} from "react";
import {AlertTriangle,BookOpen,CalendarDays,Check,ChevronLeft,ChevronRight,ClipboardCheck,Plus,Save,Search,Users} from "lucide-react";
import {activeStudents,Assignment,ASSIGNMENT_STATUSES,AttendanceRecord,ATTENDANCE_STATUSES,attendanceForDate,attendanceSummary,ClassRoom,dueSoon,localDate,moveDate,Student,SubmissionRecord,SubmissionStatus,SUBMISSION_STATUSES,submissionForAssignment,submissionSummary} from "../lib/attendance-assignment";
type Data={classes:ClassRoom[];students:Student[];attendance:AttendanceRecord[];assignments:Assignment[];submissions:SubmissionRecord[]};
type ApiPayload={error?:string;item?:ClassRoom|Student|Assignment;ok?:boolean};
const empty:Data={classes:[],students:[],attendance:[],assignments:[],submissions:[]};
export function AttendanceAssignmentManager(){
 const[data,setData]=useState(empty),[loading,setLoading]=useState(true),[authRequired,setAuthRequired]=useState(false),[error,setError]=useState(""),[tab,setTab]=useState<"attendance"|"assignments">("attendance"),[classId,setClassId]=useState(""),[date,setDate]=useState(localDate()),[dirty,setDirty]=useState(false),[saving,setSaving]=useState(false),[search,setSearch]=useState(""),[filter,setFilter]=useState("전체"),[attendanceDraft,setAttendanceDraft]=useState<AttendanceRecord[]>([]),[assignmentId,setAssignmentId]=useState(""),[submissionDraft,setSubmissionDraft]=useState<SubmissionRecord[]>([]),[selected,setSelected]=useState<string[]>([]),[showRoster,setShowRoster]=useState(false),[showAssignment,setShowAssignment]=useState(false);
 useEffect(()=>{const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),10000);fetch("/api/attendance-assignments",{cache:"no-store",signal:controller.signal}).then(async r=>{if(r.status===401){setAuthRequired(true);return;}const p=await r.json() as Data&{error?:string};if(!r.ok)throw new Error(p.error);setData(p);setClassId(p.classes[0]?.id||"");}).catch(e=>setError(e instanceof DOMException&&e.name==="AbortError"?"데이터를 불러오는 데 시간이 걸리고 있습니다. 새로고침하거나 잠시 후 다시 시도해 주세요.":e instanceof Error?e.message:"데이터를 불러오지 못했습니다.")).finally(()=>{clearTimeout(timeout);setLoading(false);});return()=>{clearTimeout(timeout);controller.abort();};},[]);
 const students=useMemo(()=>activeStudents(data.students,classId),[data.students,classId]);
 useEffect(()=>setAttendanceDraft(attendanceForDate(data.students,data.attendance,classId,date)),[data.students,data.attendance,classId,date]);
 const assignment=data.assignments.find(a=>a.id===assignmentId);
 useEffect(()=>setSubmissionDraft(assignment?submissionForAssignment(data.students,data.submissions,assignment):[]),[assignment,data.students,data.submissions]);
 const askMove=()=>!dirty||confirm("저장하지 않은 변경 사항이 있습니다. 이동할까요?");
 const post=async(body:unknown):Promise<ApiPayload>=>{const r=await fetch("/api/attendance-assignments",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),p=await r.json() as ApiPayload;if(!r.ok)throw new Error(p.error||"저장하지 못했습니다.");return p;};
 const saveAttendance=async()=>{setSaving(true);setError("");try{await post({action:"attendance",items:attendanceDraft});setData(d=>({...d,attendance:[...d.attendance.filter(r=>!(r.classId===classId&&r.attendanceDate===date)),...attendanceDraft]}));setDirty(false);}catch(e){setError(e instanceof Error?e.message:"저장하지 못했습니다.");}finally{setSaving(false);}};
 const saveSubmissions=async()=>{setSaving(true);setError("");try{await post({action:"submissions",items:submissionDraft});setData(d=>({...d,submissions:[...d.submissions.filter(r=>r.assignmentId!==assignmentId),...submissionDraft]}));setDirty(false);}catch(e){setError(e instanceof Error?e.message:"저장하지 못했습니다.");}finally{setSaving(false);}};
 const todayRecords=attendanceForDate(data.students,data.attendance,classId,localDate()),todaySummary=attendanceSummary(todayRecords),activeAssignments=data.assignments.filter(a=>a.classId===classId&&a.status==="진행 중"),missingAssignments=activeAssignments.filter(a=>submissionForAssignment(data.students,data.submissions,a).some(r=>r.status==="미제출"));
 if(loading)return <div className="aa-page"><header className="aa-header"><div><span>업무·학급 운영 · 기록/행정</span><h1>출결·과제 제출 현황</h1><p>학급의 출결과 과제 제출 상태를 불러오고 있습니다.</p></div></header><section className="aa-empty" aria-live="polite"><div className="aa-spinner"/><h2>잠시만 기다려 주세요</h2><p>학급 정보를 안전하게 불러오는 중입니다.</p></section></div>;
 if(authRequired)return <div className="aa-page"><header className="aa-header"><div><span>업무·학급 운영 · 기록/행정</span><h1>출결·과제 제출 현황</h1><p>학생 정보를 안전하게 보호하기 위해 로그인이 필요합니다.</p></div></header><section className="aa-empty"><Users/><h2>ChatGPT 로그인이 필요해요</h2><p>로그인한 교사 본인의 학급 데이터만 확인하고 관리할 수 있습니다.</p><a className="primary-btn aa-login" href="/signin-with-chatgpt?return_to=%2Fattendance-assignments">ChatGPT로 로그인</a></section></div>;
 return <div className="aa-page"><header className="aa-header"><div><span>업무·학급 운영 · 기록/행정</span><h1>출결·과제 제출 현황</h1><p>학급의 출결과 과제 제출 상태를 한 곳에서 확인하고 관리하세요.</p></div><button onClick={()=>setShowRoster(true)}><Users size={17}/> 학급·학생 관리</button></header>{error&&<div className="aa-error"><AlertTriangle size={18}/>{error}</div>}{!data.classes.length?<EmptyClass onClick={()=>setShowRoster(true)}/>:<><div className="aa-classbar"><label>학급 선택<select value={classId} onChange={e=>{if(askMove()){setClassId(e.target.value);setDirty(false)}}}>{data.classes.map(c=><option key={c.id} value={c.id}>{c.schoolYear}학년도 {c.grade}학년 {c.classNumber}반 {c.name||""}</option>)}</select></label></div><section className="aa-summary"><Summary label="오늘 미확인" value={todaySummary.미확인} icon={<ClipboardCheck/>}/><Summary label="오늘 특이 출결" value={todaySummary.결석+todaySummary.지각+todaySummary.조퇴+todaySummary.결과} icon={<CalendarDays/>}/><Summary label="진행 중 과제" value={activeAssignments.length} icon={<BookOpen/>}/><Summary label="미제출 있는 과제" value={missingAssignments.length} icon={<AlertTriangle/>}/><Summary label="3일 내 마감" value={activeAssignments.filter(a=>dueSoon(a)).length} icon={<Check/>}/></section><div className="aa-tabs"><button className={tab==="attendance"?"active":""} onClick={()=>{if(askMove()){setTab("attendance");setDirty(false)}}}>출결 관리</button><button className={tab==="assignments"?"active":""} onClick={()=>{if(askMove()){setTab("assignments");setDirty(false)}}}>과제 제출 현황</button></div>{tab==="attendance"?<AttendanceView students={students} date={date} setDate={v=>{if(askMove()){setDate(v);setDirty(false)}}} records={attendanceDraft} setRecords={v=>{setAttendanceDraft(v);setDirty(true)}} search={search} setSearch={setSearch} filter={filter} setFilter={setFilter} dirty={dirty} saving={saving} save={saveAttendance}/>:<AssignmentView assignments={data.assignments.filter(a=>a.classId===classId)} assignment={assignment} choose={id=>{if(askMove()){setAssignmentId(id);setDirty(false)}}} students={students} records={submissionDraft} setRecords={v=>{setSubmissionDraft(v);setDirty(true)}} selected={selected} setSelected={setSelected} search={search} setSearch={setSearch} filter={filter} setFilter={setFilter} dirty={dirty} saving={saving} save={saveSubmissions} create={()=>setShowAssignment(true)}/>}</>}{showRoster&&<RosterModal classId={classId} data={data} post={post} close={()=>setShowRoster(false)} update={setData} selectClass={setClassId}/>} {showAssignment&&<AssignmentModal classId={classId} post={post} close={()=>setShowAssignment(false)} add={a=>{setData(d=>({...d,assignments:[...d.assignments,a]}));setAssignmentId(a.id)}}/>}</div>;
}
function Summary({label,value,icon}:{label:string;value:number;icon:React.ReactNode}){return <article><span>{icon}</span><div><small>{label}</small><strong>{value}명</strong></div></article>}
function EmptyClass({onClick}:{onClick:()=>void}){return <section className="aa-empty"><Users/><h2>먼저 학급과 학생을 등록해 주세요</h2><p>등록한 명단을 출결과 과제 현황에서 함께 사용합니다.</p><button className="primary-btn" onClick={onClick}><Plus/>학급 만들기</button></section>}
function Toolbar({search,setSearch,filter,setFilter,statuses}:{search:string;setSearch:(v:string)=>void;filter:string;setFilter:(v:string)=>void;statuses:readonly string[]}){return <div className="aa-toolbar"><label><Search/><input aria-label="학생 검색" placeholder="번호 또는 이름 검색" value={search} onChange={e=>setSearch(e.target.value)}/></label><select aria-label="상태 필터" value={filter} onChange={e=>setFilter(e.target.value)}><option>전체</option>{statuses.map(s=><option key={s}>{s}</option>)}</select></div>}
function AttendanceView(p:{students:Student[];date:string;setDate:(v:string)=>void;records:AttendanceRecord[];setRecords:(v:AttendanceRecord[])=>void;search:string;setSearch:(v:string)=>void;filter:string;setFilter:(v:string)=>void;dirty:boolean;saving:boolean;save:()=>void}){const summary=attendanceSummary(p.records),visible=p.students.filter(s=>(!p.search||`${s.studentNumber} ${s.displayName}`.includes(p.search))&&(p.filter==="전체"||p.records.find(r=>r.studentId===s.id)?.status===p.filter));const change=(id:string,key:"status"|"note",value:string)=>p.setRecords(p.records.map(r=>r.studentId===id?{...r,[key]:value}:r));return <section className="aa-panel"><div className="aa-date"><button aria-label="이전 날짜" onClick={()=>p.setDate(moveDate(p.date,-1))}><ChevronLeft/></button><input type="date" value={p.date} onChange={e=>p.setDate(e.target.value)}/><button aria-label="다음 날짜" onClick={()=>p.setDate(moveDate(p.date,1))}><ChevronRight/></button><button onClick={()=>p.setDate(localDate())}>오늘</button></div><div className="aa-counts">{["재적",...ATTENDANCE_STATUSES].map((s,i)=><span key={s}>{s} <b>{i?summary[s as keyof typeof summary]:p.students.length}</b></span>)}</div><Toolbar search={p.search} setSearch={p.setSearch} filter={p.filter} setFilter={p.setFilter} statuses={ATTENDANCE_STATUSES}/><div className="aa-actions"><button onClick={()=>p.setRecords(p.records.map(r=>({...r,status:"출석"})))}><Check/>전체 출석</button><button className="primary-btn" disabled={!p.dirty||p.saving} onClick={p.save}><Save/>{p.saving?"저장 중":"변경 내용 저장"}</button>{p.dirty&&<em>저장하지 않은 변경 사항이 있어요.</em>}</div><StudentTable students={visible}>{s=>{const r=p.records.find(x=>x.studentId===s.id)??{classId:s.classId,studentId:s.id,attendanceDate:p.date,status:ATTENDANCE_STATUSES[0],note:""};return <><select value={r.status} onChange={e=>change(s.id,"status",e.target.value)}>{ATTENDANCE_STATUSES.map(v=><option key={v}>{v}</option>)}</select><input aria-label={`${s.displayName} 비고`} placeholder="간단한 비고" disabled={["미확인","출석"].includes(r.status)} value={r.note} onChange={e=>change(s.id,"note",e.target.value)}/></>}}</StudentTable><p className="aa-privacy">건강정보나 가정환경 등 민감한 내용은 비고에 자세히 입력하지 마세요.</p></section>}
function AssignmentView(p:{assignments:Assignment[];assignment?:Assignment;choose:(id:string)=>void;students:Student[];records:SubmissionRecord[];setRecords:(v:SubmissionRecord[])=>void;selected:string[];setSelected:(v:string[])=>void;search:string;setSearch:(v:string)=>void;filter:string;setFilter:(v:string)=>void;dirty:boolean;saving:boolean;save:()=>void;create:()=>void}){const summary=submissionSummary(p.records),visible=p.students.filter(s=>(!p.search||`${s.studentNumber} ${s.displayName}`.includes(p.search))&&(p.filter==="전체"||p.records.find(r=>r.studentId===s.id)?.status===p.filter));const bulk=(status:string,ids=p.selected.length?p.selected:p.students.map(s=>s.id))=>p.setRecords(p.records.map(r=>ids.includes(r.studentId)?{...r,status:status as SubmissionStatus}:r));return <section className="aa-panel"><div className="aa-assignment-head"><select value={p.assignment?.id||""} onChange={e=>p.choose(e.target.value)}><option value="">과제를 선택하세요</option>{p.assignments.map(a=><option key={a.id} value={a.id}>{a.title} · {a.dueDate}</option>)}</select><button onClick={p.create}><Plus/>새 과제</button></div>{!p.assignment?<div className="aa-empty small"><BookOpen/><h2>과제를 선택하거나 새로 만들어 주세요</h2></div>:<><div className="aa-counts">{["전체",...SUBMISSION_STATUSES].map((s,i)=><span key={s}>{s} <b>{i?summary[s as keyof typeof summary]:p.students.length}</b></span>)}</div><Toolbar search={p.search} setSearch={p.setSearch} filter={p.filter} setFilter={p.setFilter} statuses={SUBMISSION_STATUSES}/><div className="aa-actions"><select defaultValue="" onChange={e=>{if(e.target.value)bulk(e.target.value)}}><option value="">{p.selected.length?`선택 ${p.selected.length}명 상태 변경`:"전체 상태 일괄 변경"}</option>{SUBMISSION_STATUSES.map(v=><option key={v}>{v}</option>)}</select><button className="primary-btn" disabled={!p.dirty||p.saving} onClick={p.save}><Save/>{p.saving?"저장 중":"변경 내용 저장"}</button>{p.dirty&&<em>저장하지 않은 변경 사항이 있어요.</em>}</div><StudentTable students={visible} selectable selected={p.selected} setSelected={p.setSelected}>{s=>{const r=p.records.find(x=>x.studentId===s.id)??{assignmentId:p.assignment?.id||"",studentId:s.id,status:SUBMISSION_STATUSES[0],note:""};return <><select value={r.status} onChange={e=>p.setRecords(p.records.map(x=>x.studentId===s.id?{...x,status:e.target.value as SubmissionStatus}:x))}>{SUBMISSION_STATUSES.map(v=><option key={v}>{v}</option>)}</select><input aria-label={`${s.displayName} 비고`} placeholder="간단한 비고" value={r.note} onChange={e=>p.setRecords(p.records.map(x=>x.studentId===s.id?{...x,note:e.target.value}:x))}/></>}}</StudentTable></>}</section>}
function StudentTable({students,children,selectable=false,selected=[],setSelected=()=>{}}:{students:Student[];children:(s:Student)=>React.ReactNode;selectable?:boolean;selected?:string[];setSelected?:(v:string[])=>void}){return <div className="aa-table"><div className="aa-row aa-th">{selectable&&<span>선택</span>}<span>번호</span><span>학생</span><span>상태</span><span>비고</span></div>{students.map(s=><div className="aa-row" key={s.id}>{selectable&&<span><input type="checkbox" checked={selected.includes(s.id)} onChange={e=>setSelected(e.target.checked?[...selected,s.id]:selected.filter(v=>v!==s.id))}/></span>}<span data-label="번호">{s.studentNumber}</span><strong data-label="학생">{s.displayName}</strong>{children(s)}</div>)}</div>}
function RosterModal({classId,data,post,close,update,selectClass}:{classId:string;data:Data;post:(b:unknown)=>Promise<ApiPayload>;close:()=>void;update:React.Dispatch<React.SetStateAction<Data>>;selectClass:(v:string)=>void}){
 const[c,setC]=useState({schoolYear:new Date().getFullYear(),grade:1,classNumber:1,name:""}),[student,setStudent]=useState({studentNumber:1,displayName:""}),[busy,setBusy]=useState(false),[modalError,setModalError]=useState("");
 const run=async(task:()=>Promise<void>)=>{if(busy)return;setBusy(true);setModalError("");try{await task();}catch(error){setModalError(error instanceof Error?error.message:"저장하지 못했습니다. 다시 시도해 주세요.");}finally{setBusy(false);}};
 const addClass=()=>run(async()=>{const p=await post({action:"class",item:c}),item=p.item as ClassRoom;update(d=>({...d,classes:[...d.classes,item]}));selectClass(item.id);});
 const addStudent=()=>run(async()=>{if(!classId||!student.displayName.trim()){setModalError("학생 이름 또는 식별명을 입력해 주세요.");return;}const p=await post({action:"student",item:{...student,classId,isActive:true}}),item=p.item as Student;update(d=>({...d,students:[...d.students,item]}));setStudent({studentNumber:student.studentNumber+1,displayName:""});});
 const toggle=(s:Student)=>{if(!confirm(`${s.displayName} 학생을 ${s.isActive?"비활성":"재학"} 상태로 변경할까요?`))return;void run(async()=>{const p=await post({action:"student",item:{...s,isActive:!s.isActive}}),item=p.item as Student;update(d=>({...d,students:d.students.map(v=>v.id===s.id?item:v)}));});};
 return <div className="aa-modal"><section><button className="aa-close" onClick={close}>×</button><h2>학급·학생 관리</h2>{modalError&&<div className="aa-error" role="alert"><AlertTriangle size={17}/>{modalError}</div>}<div className="aa-inline"><input aria-label="학년도" type="number" value={c.schoolYear} onChange={e=>setC({...c,schoolYear:+e.target.value})}/><select aria-label="학년" value={c.grade} onChange={e=>setC({...c,grade:+e.target.value})}>{[1,2,3,4,5,6].map(v=><option key={v} value={v}>{v}학년</option>)}</select><input aria-label="반" type="number" min="1" value={c.classNumber} onChange={e=>setC({...c,classNumber:+e.target.value})}/><input aria-label="학급명" placeholder="학급명 (선택)" value={c.name} onChange={e=>setC({...c,name:e.target.value})}/><button disabled={busy} onClick={addClass}>{busy?"저장 중":"학급 추가"}</button></div>{classId&&<><h3>학생 명단</h3><div className="aa-inline"><input aria-label="학생 번호" type="number" min="1" value={student.studentNumber} onChange={e=>setStudent({...student,studentNumber:+e.target.value})}/><input aria-label="학생 이름" placeholder="이름 또는 식별명" value={student.displayName} onChange={e=>setStudent({...student,displayName:e.target.value})}/><button disabled={busy} onClick={addStudent}>{busy?"저장 중":"학생 추가"}</button></div><div className="aa-roster">{data.students.filter(s=>s.classId===classId).sort((a,b)=>a.studentNumber-b.studentNumber).map(s=><div key={s.id}><span>{s.studentNumber}번</span><b>{s.displayName}</b><em>{s.isActive?"재학":"비활성"}</em><button disabled={busy} onClick={()=>toggle(s)}>{s.isActive?"비활성 처리":"재학 처리"}</button></div>)}</div></>}</section></div>;
}
function AssignmentModal({classId,post,close,add}:{classId:string;post:(b:unknown)=>Promise<ApiPayload>;close:()=>void;add:(a:Assignment)=>void}){const[f,setF]=useState({classId,title:"",subject:"",description:"",assignedDate:localDate(),dueDate:"",status:"진행 중"}),[errors,setErrors]=useState<Record<string,string>>({});const save=async()=>{const e:Record<string,string>={};if(!f.title.trim())e.title="과제명을 입력해 주세요.";if(!f.dueDate)e.dueDate="제출 기한을 선택해 주세요.";setErrors(e);if(Object.keys(e).length)return;const p=await post({action:"assignment",item:f});add(p.item as Assignment);close()};return <div className="aa-modal"><section><button className="aa-close" onClick={close}>×</button><h2>새 과제 만들기</h2><div className="aa-form"><label>과제명 *<input value={f.title} onChange={e=>setF({...f,title:e.target.value})}/>{errors.title&&<small>{errors.title}</small>}</label><label>교과<input value={f.subject} onChange={e=>setF({...f,subject:e.target.value})}/></label><label>안내 내용<textarea value={f.description} onChange={e=>setF({...f,description:e.target.value})}/></label><label>제시일<input type="date" value={f.assignedDate} onChange={e=>setF({...f,assignedDate:e.target.value})}/></label><label>제출 기한 *<input type="date" value={f.dueDate} onChange={e=>setF({...f,dueDate:e.target.value})}/>{errors.dueDate&&<small>{errors.dueDate}</small>}</label><label>상태<select value={f.status} onChange={e=>setF({...f,status:e.target.value})}>{ASSIGNMENT_STATUSES.map(v=><option key={v}>{v}</option>)}</select></label></div><button className="primary-btn full" onClick={save}>과제 만들기</button></section></div>}
