/* eslint-disable @next/next/no-html-link-for-pages, react-hooks/set-state-in-effect */
"use client";
import {useEffect,useMemo,useState} from "react";
import {AlertTriangle,ArrowDown,ArrowUp,Check,Clipboard,Lock,Plus,Printer,RefreshCw,Save,Trash2,Users} from "lucide-react";
import {activeStudents,ClassRoom,Student,localDate} from "../lib/attendance-assignment";
import {allocateRoles,capacityDelta,ClassRole,duplicateChoices,periodOverlaps,RoleAssignment,RoleCycle,RoleHistory,RolePreference,validateAssignments} from "../lib/role-assignment";
type Data={classes:ClassRoom[];students:Student[];roles:ClassRole[];cycles:RoleCycle[];preferences:RolePreference[];assignments:(RoleAssignment&{cycleId:string})[];history:RoleHistory[]};
const empty:Data={classes:[],students:[],roles:[],cycles:[],preferences:[],assignments:[],history:[]};
const blankRole=(classId:string,order:number):ClassRole=>({id:"",classId,name:"",description:"",capacity:1,displayOrder:order,isActive:true});
const blankCycle=(classId:string):RoleCycle=>({id:"",classId,name:"",startDate:localDate(),endDate:localDate(),note:"",status:"draft"});
const prefFor=(studentId:string,items:RolePreference[])=>items.find(p=>p.studentId===studentId)??{studentId,excludedRoleIds:[],note:""};

export function ClassRoleAssignment(){
 const[data,setData]=useState(empty),[loading,setLoading]=useState(true),[auth,setAuth]=useState(false),[error,setError]=useState(""),[busy,setBusy]=useState(false),[classId,setClassId]=useState(""),[roleDraft,setRoleDraft]=useState<ClassRole>(blankRole("",0)),[cycle,setCycle]=useState<RoleCycle>(blankCycle("")),[preferences,setPreferences]=useState<RolePreference[]>([]),[assignments,setAssignments]=useState<RoleAssignment[]>([]),[failure,setFailure]=useState<string[]>([]),[view,setView]=useState<"student"|"role">("student"),[dirty,setDirty]=useState(false),[copied,setCopied]=useState("");
 useEffect(()=>{fetch("/api/class-roles",{cache:"no-store"}).then(async r=>{if(r.status===401){setAuth(true);return;}const p=await r.json() as Data&{error?:string};if(!r.ok)throw new Error(p.error);setData(p);const id=p.classes[0]?.id||"";setClassId(id);}).catch(e=>setError(e instanceof Error?e.message:"데이터를 불러오지 못했습니다.")).finally(()=>setLoading(false));},[]);
 useEffect(()=>{if(!classId)return;const existing=data.cycles.find(c=>c.classId===classId);setCycle(existing??blankCycle(classId));setRoleDraft(blankRole(classId,0));if(existing){setPreferences(data.preferences.filter(p=>p.cycleId===existing.id));setAssignments(data.assignments.filter(a=>a.cycleId===existing.id));}else{setPreferences([]);setAssignments([]);}setDirty(false);
 // eslint-disable-next-line react-hooks/exhaustive-deps -- only re-pick a default cycle when the class changes; saving/creating a cycle already sets state explicitly and must not be overridden by this effect re-running
 },[classId]);
 useEffect(()=>{const leave=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue="";}};addEventListener("beforeunload",leave);return()=>removeEventListener("beforeunload",leave);},[dirty]);
 useEffect(()=>{const toggle=(event:MouseEvent)=>{const option=(event.target as HTMLElement).closest(".pref-row select[multiple] option") as HTMLOptionElement|null;if(!option)return;event.preventDefault();option.selected=!option.selected;option.parentElement?.dispatchEvent(new Event("change",{bubbles:true}));};document.addEventListener("mousedown",toggle);return()=>document.removeEventListener("mousedown",toggle);},[]);
 const classroom=data.classes.find(c=>c.id===classId),students=useMemo(()=>activeStudents(data.students,classId),[data.students,classId]),roles=data.roles.filter(r=>r.classId===classId).sort((a,b)=>a.displayOrder-b.displayOrder),activeRoles=roles.filter(r=>r.isActive),delta=capacityDelta(activeRoles,students.length),overlap=cycle.startDate&&cycle.endDate&&periodOverlaps(cycle.startDate,cycle.endDate,data.cycles.filter(c=>c.classId===classId),cycle.id),invalidPrefs=preferences.some(duplicateChoices),blocked=students.filter(s=>activeRoles.every(r=>prefFor(s.id,preferences).excludedRoleIds.includes(r.id)));
 const post=async(body:unknown)=>{const r=await fetch("/api/class-roles",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),p=await r.json() as {error?:string;item?:unknown};if(!r.ok)throw new Error(p.error||"저장하지 못했습니다.");return p;};
 const run=async(task:()=>Promise<void>)=>{if(busy)return;setBusy(true);setError("");try{await task();}catch(e){setError(e instanceof Error?e.message:"처리하지 못했습니다. 다시 시도해 주세요.");}finally{setBusy(false);}};
 const saveRole=()=>run(async()=>{if(!roleDraft.name.trim()){setError("역할명을 입력해 주세요.");return;}const p=await post({action:"role",item:roleDraft}),item=p.item as ClassRole;setData(d=>({...d,roles:roleDraft.id?d.roles.map(r=>r.id===item.id?item:r):[...d.roles,item]}));setRoleDraft(blankRole(classId,roles.length+1));});
 const removeRole=(role:ClassRole)=>{if(!confirm(`'${role.name}' 역할을 삭제할까요? 저장된 배정에서 사용 중이면 삭제할 수 없습니다.`))return;void run(async()=>{await post({action:"delete-role",id:role.id});setData(d=>({...d,roles:d.roles.filter(r=>r.id!==role.id)}));});};
 const moveRole=(role:ClassRole,step:number)=>{const target=roles[roles.indexOf(role)+step];if(!target)return;void run(async()=>{const a={...role,displayOrder:target.displayOrder},b={...target,displayOrder:role.displayOrder};await post({action:"role",item:a});await post({action:"role",item:b});setData(d=>({...d,roles:d.roles.map(r=>r.id===a.id?a:r.id===b.id?b:r)}));});};
 const saveCycle=()=>run(async()=>{if(!cycle.name.trim()||!cycle.startDate||!cycle.endDate||cycle.startDate>cycle.endDate){setError("회차명과 올바른 시작일·종료일을 입력해 주세요.");return;}const p=await post({action:"cycle",item:cycle}),item=p.item as RoleCycle;setCycle(item);setData(d=>({...d,cycles:cycle.id?d.cycles.map(c=>c.id===item.id?item:c):[item,...d.cycles]}));setDirty(false);alert("회차 정보가 저장되었습니다.");});
 const chooseCycle=(id:string)=>{if(dirty&&!confirm("저장하지 않은 변경 사항이 있습니다. 회차를 바꿀까요?"))return;if(!id){setCycle(blankCycle(classId));setPreferences([]);setAssignments([]);setDirty(false);return;}const found=data.cycles.find(c=>c.id===id);if(!found)return;setCycle(found);setPreferences(data.preferences.filter(p=>p.cycleId===id));setAssignments(data.assignments.filter(a=>a.cycleId===id));setDirty(false);};
 const changePref=(studentId:string,patch:Partial<RolePreference>)=>{const next={...prefFor(studentId,preferences),...patch};setPreferences([...preferences.filter(p=>p.studentId!==studentId),next]);setDirty(true);};
 const savePrefs=()=>run(async()=>{if(!cycle.id){setError("배정 회차를 먼저 저장해 주세요.");return;}if(invalidPrefs){setError("같은 희망 역할을 여러 순위에 선택할 수 없습니다.");return;}await post({action:"preferences",cycleId:cycle.id,items:preferences});setDirty(false);});
 const allocate=(onlyUnlocked=false)=>{setFailure([]);const lockedPrefs=preferences.map(p=>{const current=assignments.find(a=>a.studentId===p.studentId);return onlyUnlocked&&current?.isLocked?{...p,lockedRoleId:current.roleId}:p;});const result=allocateRoles({students,roles:activeRoles,preferences:lockedPrefs,history:data.history});if(!result.ok){setFailure(result.failure.messages);return;}setAssignments(result.assignments);setDirty(true);};
 const changeAssignment=(studentId:string,roleId:string)=>{const current=assignments.find(a=>a.studentId===studentId);if(!current||current.roleId===roleId)return;if(prefFor(studentId,preferences).excludedRoleIds.includes(roleId)){setError("이 학생에게 배정 제외된 역할입니다.");return;}const partner=assignments.find(a=>a.roleId===roleId&&!a.isLocked&&!prefFor(a.studentId,preferences).excludedRoleIds.includes(current.roleId));if(!partner){setError("맞바꿀 수 있는 학생이 없습니다. 고정 또는 제외 조건을 확인해 주세요.");return;}const next=assignments.map(a=>a.studentId===studentId?{...a,roleId,assignmentSource:"manual" as const}:a.studentId===partner.studentId?{...a,roleId:current.roleId,assignmentSource:"manual" as const}:a),errors=validateAssignments(students,activeRoles,preferences,next);if(errors.length){setError(errors[0]);return;}setAssignments(next);setDirty(true);};
 const toggleLock=(studentId:string)=>{setAssignments(assignments.map(a=>a.studentId===studentId?{...a,isLocked:!a.isLocked}:a));setDirty(true);};
 const confirmAll=()=>run(async()=>{if(!cycle.id){setError("회차를 먼저 저장해 주세요.");return;}const errors=validateAssignments(students,activeRoles,preferences,assignments);if(errors.length){setError(errors[0]);return;}if(!confirm("현재 배정 결과를 확정하고 저장할까요?"))return;await post({action:"preferences",cycleId:cycle.id,items:preferences});await post({action:"confirm",cycle,items:assignments,preferences});setCycle({...cycle,status:"confirmed"});setDirty(false);});
 const roleName=(id:string)=>roles.find(r=>r.id===id)?.name||"-",previous=(studentId:string)=>data.history.filter(h=>h.studentId===studentId).sort((a,b)=>b.cycleStartDate.localeCompare(a.cycleStartDate))[0],choiceRank=(studentId:string,roleId:string)=>{const p=prefFor(studentId,preferences);return p.firstChoiceRoleId===roleId?"1순위":p.secondChoiceRoleId===roleId?"2순위":p.thirdChoiceRoleId===roleId?"3순위":"희망 외";};
 const copy=async(kind:"student"|"role")=>{const text=kind==="student"?students.map(s=>`${s.studentNumber}번 ${s.displayName}: ${roleName(assignments.find(a=>a.studentId===s.id)?.roleId||"")}`).join("\n"):activeRoles.map(r=>`${r.name}: ${students.filter(s=>assignments.find(a=>a.studentId===s.id)?.roleId===r.id).map(s=>s.displayName).join(", ")}`).join("\n");await navigator.clipboard.writeText(text);setCopied(kind);setTimeout(()=>setCopied(""),1800);};
 if(loading)return <div className="role-page role-empty">학급과 역할 정보를 불러오는 중입니다.</div>;if(auth)return <div className="role-page role-empty"><Users/><h2>로그인이 필요해요</h2><a className="primary-btn" href="/login?returnTo=%2Fclass-roles">로그인하기</a></div>;
 return <div className="role-page"><header className="role-header"><div><span>업무·학급 운영 · 학급관리</span><h1>1인 1역 배정 도우미</h1><p>학생의 희망과 이전 역할을 고려해 한 명당 하나의 역할을 공정하게 배정해요.</p></div><span className="role-no-ai">AI 및 학생 평가 정보 미사용</span></header><div className="role-steps">{["학급 선택","역할 구성","희망·조건","자동 배정","결과 수정","배정 확정"].map((s,i)=><span className={assignments.length?i<5?"done":"active":cycle.id?i<3?"done":i===3?"active":"":i===0?"active":""} key={s}><b>{i+1}</b>{s}</span>)}</div>{error&&<div className="aa-error"><AlertTriangle/>{error}</div>}{!data.classes.length?<section className="role-empty"><Users/><h2>먼저 공통 학급·학생 관리에서 명단을 등록해 주세요.</h2><a className="primary-btn" href="/class-management">학급·학생 관리로 이동</a></section>:<><section className="role-card role-class"><label>학급 선택<select value={classId} onChange={e=>{if(!dirty||confirm("저장하지 않은 변경 사항이 있습니다. 학급을 바꿀까요?"))setClassId(e.target.value)}}>{data.classes.map(c=><option key={c.id} value={c.id}>{c.schoolYear}학년도 {c.grade}학년 {c.classNumber}반 {c.name||""}</option>)}</select></label><a className="outline-btn" href="/class-management">학급·학생 명단 관리</a><div><b>{classroom?.grade}학년 {classroom?.classNumber}반</b><span>재학 중 {students.length}명 · 비활성 학생 제외</span></div></section>
 <section className="role-card"><div className="role-title"><div><span>STEP 2</span><h2>역할 구성</h2></div><strong className={delta===0?"ok":"warn"}>{delta===0?`배정 가능 · ${students.length}자리`:delta<0?`${-delta}자리 부족`:`${delta}자리 남음`}</strong></div><div className="role-list">{roles.map((r,i)=><div key={r.id} className={!r.isActive?"off":""}><button onClick={()=>setRoleDraft(r)}><b>{r.name}</b><span>{r.description||"설명 없음"}</span><em>{r.capacity}명 · {r.isActive?"사용":"미사용"}</em></button><div><button aria-label="위로" onClick={()=>moveRole(r,-1)} disabled={!i}><ArrowUp/></button><button aria-label="아래로" onClick={()=>moveRole(r,1)} disabled={i===roles.length-1}><ArrowDown/></button><button aria-label="삭제" onClick={()=>removeRole(r)}><Trash2/></button></div></div>)}</div><div className="role-form"><input placeholder="역할명 *" value={roleDraft.name} onChange={e=>setRoleDraft({...roleDraft,name:e.target.value})}/><input placeholder="역할 설명 (선택)" value={roleDraft.description} onChange={e=>setRoleDraft({...roleDraft,description:e.target.value})}/><label>인원<input type="number" min="1" value={roleDraft.capacity} onChange={e=>setRoleDraft({...roleDraft,capacity:+e.target.value})}/></label><label><input type="checkbox" checked={roleDraft.isActive} onChange={e=>setRoleDraft({...roleDraft,isActive:e.target.checked})}/> 사용</label><button onClick={saveRole} disabled={busy}><Plus/>{roleDraft.id?"수정 저장":"역할 추가"}</button></div></section>
 <section className="role-card"><div className="role-title"><div><span>배정 기간</span><h2>회차 정보</h2></div><div className="result-actions"><select value={cycle.id} onChange={e=>chooseCycle(e.target.value)}><option value="">새 회차 만들기</option>{data.cycles.filter(c=>c.classId===classId).map(c=><option key={c.id} value={c.id}>{c.name} · {c.startDate}</option>)}</select>{cycle.status==="confirmed"&&<strong className="ok">확정됨</strong>}</div></div><div className="cycle-form"><label>회차명 *<input placeholder="예: 1학기 1차" value={cycle.name} onChange={e=>{setCycle({...cycle,name:e.target.value});setDirty(true)}}/></label><label>시작일 *<input type="date" value={cycle.startDate} onChange={e=>{setCycle({...cycle,startDate:e.target.value});setDirty(true)}}/></label><label>종료일 *<input type="date" value={cycle.endDate} onChange={e=>{setCycle({...cycle,endDate:e.target.value});setDirty(true)}}/></label><label>비고<input value={cycle.note} onChange={e=>{setCycle({...cycle,note:e.target.value});setDirty(true)}}/></label></div>{overlap&&<p className="role-warning">같은 학급의 기존 배정 회차와 기간이 겹칩니다.</p>}<button className="outline-btn" disabled={busy} onClick={saveCycle}><Save/>회차 저장</button></section>
 <section className="role-card"><div className="role-title"><div><span>STEP 3</span><h2>학생 희망 및 배정 조건</h2></div><button className="outline-btn" onClick={savePrefs} disabled={busy||!cycle.id}><Save/>조건 저장</button></div><p className="role-help">희망은 가능한 범위에서 반영됩니다. 제외 메모에는 건강정보·장애·가정환경 등 민감한 개인정보를 자세히 입력하지 마세요.</p><div className="pref-table"><div className="pref-row head"><span>학생</span><span>1순위</span><span>2순위</span><span>3순위</span><span>제외 역할</span><span>고정</span></div>{students.map(s=>{const p=prefFor(s.id,preferences);return <div className="pref-row" key={s.id}><b>{s.studentNumber}번 {s.displayName}</b>{(["firstChoiceRoleId","secondChoiceRoleId","thirdChoiceRoleId"] as const).map(k=><select key={k} value={p[k]||""} onChange={e=>changePref(s.id,{[k]:e.target.value||undefined})}><option value="">선택 안 함</option>{activeRoles.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select>)}<select multiple value={p.excludedRoleIds} onChange={e=>changePref(s.id,{excludedRoleIds:Array.from(e.target.selectedOptions,o=>o.value)})}>{activeRoles.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select><select value={p.lockedRoleId||""} onChange={e=>changePref(s.id,{lockedRoleId:e.target.value||undefined})}><option value="">없음</option>{activeRoles.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></div>})}</div>{invalidPrefs&&<p className="role-warning">동일한 역할을 여러 희망 순위에 중복 선택한 학생이 있습니다.</p>}{blocked.length>0&&<p className="role-warning">배정 가능한 역할이 없는 학생: {blocked.map(s=>`${s.studentNumber}번 ${s.displayName}`).join(", ")}</p>}</section>
 <section className="role-card role-allocate"><div><h2>자동 배정</h2><p>조건이 없어도 역할 정원에 맞춰 공정하게 배정합니다. 입력한 희망·고정·제외 조건이 있으면 함께 반영합니다.</p>{!cycle.id&&<small>회차를 저장하지 않아도 미리 배정할 수 있으며, 최종 확정 전에는 회차 저장이 필요합니다.</small>}</div><button className="primary-btn" disabled={busy||delta!==0||invalidPrefs||blocked.length>0||!students.length} onClick={()=>allocate(false)}><RefreshCw/>자동 배정하기</button>{failure.length>0&&<div className="allocation-failure"><AlertTriangle/><div><b>전체 배정이 불가능합니다.</b>{failure.map(m=><p key={m}>{m}</p>)}</div></div>}</section>
 {assignments.length>0&&<section className="role-card role-results"><div className="role-title"><div><span>STEP 5–6</span><h2>배정 결과 확인 및 수정</h2></div><div className="result-actions"><button onClick={()=>setView(view==="student"?"role":"student")}>{view==="student"?"역할별 보기":"학생별 보기"}</button><button onClick={()=>allocate(true)}><Lock/>고정 제외 재배정</button><button onClick={()=>allocate(false)}><RefreshCw/>전체 재배정</button></div></div><div className="role-summary"><span>전체 <b>{students.length}</b></span><span>배정 완료 <b>{assignments.length}</b></span><span>1순위 <b>{assignments.filter(a=>choiceRank(a.studentId,a.roleId)==="1순위").length}</b></span><span>2·3순위 <b>{assignments.filter(a=>["2순위","3순위"].includes(choiceRank(a.studentId,a.roleId))).length}</b></span><span>희망 외 <b>{assignments.filter(a=>choiceRank(a.studentId,a.roleId)==="희망 외").length}</b></span><span>이전 역할 반복 <b>{assignments.filter(a=>previous(a.studentId)?.roleId===a.roleId).length}</b></span></div>{view==="student"?<div className="result-table">{students.map(s=>{const a=assignments.find(v=>v.studentId===s.id)!;return <div key={s.id}><b>{s.studentNumber}번 {s.displayName}</b><select value={a.roleId} onChange={e=>changeAssignment(s.id,e.target.value)}>{activeRoles.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select><span>{choiceRank(s.id,a.roleId)}</span><span>이전: {roleName(previous(s.id)?.roleId||"")}</span><button className={a.isLocked?"locked":""} onClick={()=>toggleLock(s.id)}><Lock/>{a.isLocked?"고정됨":"고정"}</button></div>})}</div>:<div className="role-group-view">{activeRoles.map(r=><article key={r.id}><h3>{r.name}<small>{assignments.filter(a=>a.roleId===r.id).length}/{r.capacity}명</small></h3><p>{r.description}</p><b>{students.filter(s=>assignments.find(a=>a.studentId===s.id)?.roleId===r.id).map(s=>`${s.studentNumber}번 ${s.displayName}`).join(", ")}</b></article>)}</div>}<div className="role-footer"><button onClick={()=>copy(view)}><Clipboard/>{copied?"복사 완료":"현재 보기 복사"}</button><button onClick={()=>print()}><Printer/>인쇄</button><button onClick={()=>{if(confirm("현재 배정 결과를 취소할까요?")){setAssignments([]);setDirty(false)}}}>배정 취소</button><button className="primary-btn" disabled={busy||validateAssignments(students,activeRoles,preferences,assignments).length>0} onClick={confirmAll}><Check/>배정 확정</button></div></section>}</>}</div>;
}
