"use client";
import { useState } from "react";
import { AlertCircle,Check,LoaderCircle,Printer,RefreshCw,Sparkles } from "lucide-react";
import { FieldError } from "./generator-result";
import { ASSESSMENT_METHODS,ASSESSMENT_MODES,ASSESSMENT_TIMINGS,PERFORMANCE_DOMAINS,type AssessmentMethod } from "../lib/korean-performance-config";
import { defaultPerformanceLevelNames,mergePerformanceSection,performancePrintIssues,validatePerformanceAssessmentInput,type PerformanceAssessment,type PerformanceAssessmentErrors,type PerformanceAssessmentInput,type RubricCriterion } from "../lib/korean-performance-assessment";

const initial:PerformanceAssessmentInput={semester:"학기 구분 없이",unit:"",lesson:"",domain:"읽기",achievementStandard:"",learningGoal:"",assessmentElements:["내용 확인하기"],topic:"",sourceText:"",additionalRequest:"",methods:["관찰평가","활동지형 수행평가"],mode:"개인",durationMinutes:20,timing:"수업 중",customTiming:"",levelCount:3,levelNames:defaultPerformanceLevelNames(3),scoreMode:"성취수준만 사용",totalScore:30,elementScores:[30]};
const steps=["평가 기본 정보 입력","평가 방법과 기준 설정","수행평가 생성","내용 확인 및 수정","학생용·교사용 미리보기","인쇄"];
type Tab="overview"|"student"|"rubric"|"checklist"|"teacher";
type PartialSection="task"|"rubric"|"checklist"|"feedback";

export function KoreanPerformanceAssessmentGenerator(){
 const[form,setForm]=useState(initial),[errors,setErrors]=useState<PerformanceAssessmentErrors>({}),[result,setResult]=useState<PerformanceAssessment|null>(null),[loading,setLoading]=useState(false),[busy,setBusy]=useState<PartialSection|null>(null),[apiError,setApiError]=useState(""),[tab,setTab]=useState<Tab>("overview");
 const current=loading?3:result?4:1;
 const update=<K extends keyof PerformanceAssessmentInput>(key:K,value:PerformanceAssessmentInput[K])=>{setForm(c=>({...c,[key]:value}));setErrors(c=>({...c,[key]:undefined}))};
 const toggleMethod=(x:AssessmentMethod)=>update("methods",form.methods.includes(x)?form.methods.filter(v=>v!==x):[...form.methods,x]);
 const setElements=(text:string)=>{const next=text.split("\n").map(x=>x.trim()).filter(Boolean).slice(0,3);setForm(c=>({...c,assessmentElements:next,elementScores:next.map((_,i)=>c.elementScores[i]||10)}));setErrors(c=>({...c,assessmentElements:undefined,elementScores:undefined}))};
 const setLevelCount=(count:3|4)=>setForm(c=>({...c,levelCount:count,levelNames:defaultPerformanceLevelNames(count)}));
 const request=async(section:"all"|PartialSection,currentResult?:PerformanceAssessment)=>{const response=await fetch("/api/korean-performance-assessments/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({input:form,section,current:currentResult})});const payload=await response.json() as {assessment?:PerformanceAssessment;error?:string;fields?:PerformanceAssessmentErrors};if(!response.ok||!payload.assessment){if(payload.fields)setErrors(payload.fields);throw new Error(payload.error||"수행평가를 생성하지 못했습니다.")}return payload.assessment};
 const generate=async()=>{const checked=validatePerformanceAssessmentInput(form);setErrors(checked.errors);setApiError("");if(!checked.data)return;setLoading(true);try{setResult(await request("all"));setTab("overview")}catch(error){setApiError(error instanceof Error?error.message:"수행평가를 생성하지 못했습니다.")}finally{setLoading(false)}};
 const regenerate=async(section:PartialSection)=>{if(!result)return;setBusy(section);setApiError("");try{const next=await request(section,result);setResult(mergePerformanceSection(result,next,section))}catch(error){setApiError(error instanceof Error?error.message:"선택한 부분을 다시 생성하지 못했습니다.")}finally{setBusy(null)}};
 const edit=(fn:(x:PerformanceAssessment)=>PerformanceAssessment)=>setResult(c=>c?fn(c):c);
 const print=(target:"student"|"teacher"|"rubric"|"all")=>{if(!result)return;const issue=performancePrintIssues(result,form)[0];if(issue){setApiError(`인쇄 전에 확인해 주세요: ${issue}`);return}document.documentElement.dataset.paPrint=target;window.addEventListener("afterprint",()=>delete document.documentElement.dataset.paPrint,{once:true});window.print()};
 return <div className="pa-page"><header className="page-head"><div><span className="eyebrow">수업 도우미 · 국어</span><h1>1학년 국어 수행평가 생성기</h1><p>성취기준과 평가 요소가 연결된 학생용 과제와 교사용 평가계획을 만들어요.</p></div><span className="privacy-note"><Check size={15}/> 학생 정보와 결과를 저장하지 않아요</span></header>
  <div className="pa-ethics"><AlertCircle/><div><b>교사가 검토하고 수정하는 평가 초안입니다.</b><p>학생 이름·답안·점수는 입력하지 마세요. AI는 학생을 자동 평가하거나 성취수준을 결정하지 않습니다.</p></div></div>
  <nav className="pa-steps" aria-label="수행평가 생성 단계">{steps.map((x,i)=><span className={i+1===current?"current":i+1<current?"done":""} key={x}><b>{i+1}</b>{x}</span>)}</nav>
  <div className="pa-layout"><aside className="pa-controls"><section className="dm-card"><h2><span>1</span> 평가 기본 정보</h2><div className="pa-fixed"><b>초등학교</b><b>1학년</b><b>국어</b></div><div className="dm-form-grid"><Select label="학기" value={form.semester} onChange={v=>update("semester",v as PerformanceAssessmentInput["semester"])}><option>1학기</option><option>2학기</option><option>학기 구분 없이</option></Select><Text label="단원명" optional value={form.unit||""} onChange={v=>update("unit",v)}/><Text label="차시" optional value={form.lesson||""} onChange={v=>update("lesson",v)}/><Select label="국어 영역 *" value={form.domain} onChange={v=>update("domain",v as PerformanceAssessmentInput["domain"])}>{PERFORMANCE_DOMAINS.map(x=><option key={x}>{x}</option>)}</Select></div><TextArea label="성취기준 *" value={form.achievementStandard} onChange={v=>update("achievementStandard",v)} error={errors.achievementStandard} placeholder="입력한 문구를 그대로 사용합니다."/><TextArea label="학습 목표" optional value={form.learningGoal||""} onChange={v=>update("learningGoal",v)}/><TextArea label="평가 요소 *" value={form.assessmentElements.join("\n")} onChange={setElements} error={errors.assessmentElements} placeholder="줄마다 한 개씩, 최대 3개"/><TextArea label="평가 주제 또는 핵심 내용 *" value={form.topic} onChange={v=>update("topic",v)} error={errors.topic}/><TextArea label="제시문·학습 자료" optional value={form.sourceText||""} onChange={v=>update("sourceText",v)} placeholder="그림이 필요한 과제는 생성하지 않습니다."/><TextArea label="교사의 추가 요청" optional value={form.additionalRequest||""} onChange={v=>update("additionalRequest",v)}/></section>
  <section className="dm-card"><h2><span>2</span> 평가 방법과 기준</h2><fieldset><legend>평가 방법 *</legend><div className="pa-choice-grid">{ASSESSMENT_METHODS.map(x=><button type="button" className={form.methods.includes(x)?"selected":""} onClick={()=>toggleMethod(x)} key={x}>{x}</button>)}</div><FieldError message={errors.methods}/></fieldset><div className="dm-form-grid"><Select label="평가 방식" value={form.mode} onChange={v=>update("mode",v as PerformanceAssessmentInput["mode"])}>{ASSESSMENT_MODES.map(x=><option key={x}>{x}</option>)}</Select><label className="dm-field"><span>평가 시간(분)</span><input type="number" min="1" value={form.durationMinutes} onChange={e=>update("durationMinutes",Number(e.target.value))}/><FieldError message={errors.durationMinutes}/></label><Select label="평가 실시 시기" value={form.timing} onChange={v=>update("timing",v as PerformanceAssessmentInput["timing"])}>{ASSESSMENT_TIMINGS.map(x=><option key={x}>{x}</option>)}</Select>{form.timing==="직접 입력"&&<Text label="실시 시기 직접 입력" value={form.customTiming||""} onChange={v=>update("customTiming",v)}/>}</div><label className="dm-field"><span>성취수준 단계</span><div className="pa-segment"><button className={form.levelCount===3?"selected":""} onClick={()=>setLevelCount(3)}>3단계</button><button className={form.levelCount===4?"selected":""} onClick={()=>setLevelCount(4)}>4단계</button></div></label><div className="pa-level-names">{form.levelNames.map((x,i)=><label key={i}><span>{i+1}단계</span><input value={x} onChange={e=>update("levelNames",form.levelNames.map((v,n)=>n===i?e.target.value:v))}/></label>)}</div><FieldError message={errors.levelNames}/><Select label="평가 결과 방식" value={form.scoreMode} onChange={v=>update("scoreMode",v as PerformanceAssessmentInput["scoreMode"])}><option>성취수준만 사용</option><option>점수와 성취수준 함께 사용</option></Select>{form.scoreMode==="점수와 성취수준 함께 사용"&&<div className="pa-scores"><label><span>총점</span><input type="number" min="1" value={form.totalScore||""} onChange={e=>update("totalScore",Number(e.target.value))}/></label>{form.assessmentElements.map((x,i)=><label key={`${x}-${i}`}><span>{x} 배점</span><input type="number" min="1" value={form.elementScores[i]||""} onChange={e=>update("elementScores",form.elementScores.map((v,n)=>n===i?Number(e.target.value):v))}/></label>)}<FieldError message={errors.elementScores}/></div>}<button className="primary-btn full pa-generate" disabled={loading} onClick={generate}>{loading?<><LoaderCircle className="spin"/> 수행평가를 만들고 있어요</>:<><Sparkles/> 수행평가 생성</>}</button>{apiError&&<div className="pa-error"><AlertCircle/>{apiError}<button onClick={generate}>다시 시도</button></div>}</section></aside>
  <main className="pa-workspace">{!result?<div className="dm-empty"><span><Sparkles/></span><h2>1학년 국어 수행평가를 만들어 보세요</h2><p>성취기준과 평가 요소를 입력하면<br/>학생용 과제와 교사용 채점기준이 함께 나타납니다.</p></div>:<><div className="pa-toolbar"><div className="pa-tabs">{([['overview','평가 개요'],['student','학생용 수행평가'],['rubric','채점기준'],['checklist','관찰 체크리스트'],['teacher','교사용 자료']] as [Tab,string][]).map(([id,label])=><button className={tab===id?"active":""} onClick={()=>setTab(id)} key={id}>{label}</button>)}</div><div className="pa-print-buttons"><button onClick={()=>print("student")}><Printer/>학생용</button><button onClick={()=>print("teacher")}><Printer/>교사용</button><button onClick={()=>print("rubric")}><Printer/>채점기준·관찰표</button><button onClick={()=>print("all")}><Printer/>전체</button></div></div><div className="pa-regenerate"><button disabled={!!busy} onClick={()=>regenerate("task")}><RefreshCw/> 수행 과제만</button><button disabled={!!busy} onClick={()=>regenerate("rubric")}><RefreshCw/> 채점기준만</button><button disabled={!!busy} onClick={()=>regenerate("checklist")}><RefreshCw/> 관찰표만</button><button disabled={!!busy} onClick={()=>regenerate("feedback")}><RefreshCw/> 피드백만</button><button disabled={loading||!!busy} onClick={generate}><RefreshCw/> 전체 다시</button>{busy&&<span><LoaderCircle className="spin"/> 선택한 부분을 만들고 있어요</span>}</div><EditPanel tab={tab} result={result} edit={edit}/><PrintPreview result={result} input={form} tab={tab}/></>}</main></div></div>;
}

function Select({label,value,onChange,children}:{label:string;value:string|number;onChange:(v:string)=>void;children:React.ReactNode}){return <label className="dm-field"><span>{label}</span><select value={value} onChange={e=>onChange(e.target.value)}>{children}</select></label>}
function Text({label,value,onChange,optional}:{label:string;value:string;onChange:(v:string)=>void;optional?:boolean}){return <label className="dm-field"><span>{label}{optional&&<small> 선택</small>}</span><input value={value} onChange={e=>onChange(e.target.value)}/></label>}
function TextArea({label,value,onChange,optional,error,placeholder}:{label:string;value:string;onChange:(v:string)=>void;optional?:boolean;error?:string;placeholder?:string}){return <label className="dm-field"><span>{label}{optional&&<small> 선택</small>}</span><textarea value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/><FieldError message={error}/></label>}
const Lines=({value,onChange}:{value:string[];onChange:(x:string[])=>void})=><textarea value={value.join("\n")} onChange={e=>onChange(e.target.value.split("\n").filter(Boolean))}/>;
function EditPanel({tab,result,edit}:{tab:Tab;result:PerformanceAssessment;edit:(fn:(x:PerformanceAssessment)=>PerformanceAssessment)=>void}){
 if(tab==="overview")return <section className="pa-editor"><h2>평가 개요</h2><label>평가 제목<input value={result.title} onChange={e=>edit(x=>({...x,title:e.target.value}))}/></label><div className="pa-summary"><p><b>성취기준</b>{result.overview.achievementStandard}</p><p><b>평가 요소</b>{result.overview.assessmentElements.join(", ")}</p><p><b>방법·시기</b>{result.overview.assessmentMethods.join(", ")} · {result.overview.timing}</p></div></section>;
 if(tab==="student")return <section className="pa-editor"><h2>학생용 수행평가</h2><label>학생용 안내문<textarea value={result.studentWorksheet.introduction} onChange={e=>edit(x=>({...x,studentWorksheet:{...x.studentWorksheet,introduction:e.target.value}}))}/></label><label>수행 단계<Lines value={result.studentTask.steps} onChange={v=>edit(x=>({...x,studentTask:{...x.studentTask,steps:v}}))}/></label>{result.studentWorksheet.tasks.map((task,i)=><article key={task.id}><b>{task.id}</b><textarea value={task.instruction} onChange={e=>edit(x=>({...x,studentWorksheet:{...x.studentWorksheet,tasks:x.studentWorksheet.tasks.map((t,n)=>n===i?{...t,instruction:e.target.value}:t)}}))}/><label>답안 줄 수 <input type="number" min="1" max="12" value={task.answerSpaceLines} onChange={e=>edit(x=>({...x,studentWorksheet:{...x.studentWorksheet,tasks:x.studentWorksheet.tasks.map((t,n)=>n===i?{...t,answerSpaceLines:Number(e.target.value)}:t)}}))}/></label></article>)}</section>;
 if(tab==="rubric")return <section className="pa-editor"><h2>채점기준</h2>{result.rubric.map((criterion,i)=><RubricEditor key={criterion.criterionId} criterion={criterion} onChange={next=>edit(x=>({...x,rubric:x.rubric.map((r,n)=>n===i?next:r)}))}/>)}</section>;
 if(tab==="checklist")return <section className="pa-editor"><h2>관찰 체크리스트</h2>{result.observationChecklist.map((item,i)=><article key={`${item.criterionId}-${i}`}><b>{item.criterionId}</b><textarea value={item.observableBehavior} onChange={e=>edit(x=>({...x,observationChecklist:x.observationChecklist.map((v,n)=>n===i?{...v,observableBehavior:e.target.value}:v)}))}/></article>)}</section>;
 return <section className="pa-editor"><h2>교사용 자료</h2><label>평가 의도<textarea value={result.teacherGuide.intent} onChange={e=>edit(x=>({...x,teacherGuide:{...x.teacherGuide,intent:e.target.value}}))}/></label><label>진행 절차<Lines value={result.teacherGuide.procedure} onChange={v=>edit(x=>({...x,teacherGuide:{...x.teacherGuide,procedure:v}}))}/></label><label>평가 유의사항<Lines value={result.teacherGuide.cautions} onChange={v=>edit(x=>({...x,teacherGuide:{...x.teacherGuide,cautions:v}}))}/></label><label>예시 답안<Lines value={result.teacherGuide.sampleAnswers.map(x=>`${x.taskId}: ${x.answer}`)} onChange={v=>edit(x=>({...x,teacherGuide:{...x.teacherGuide,sampleAnswers:v.map(line=>{const [taskId,...rest]=line.split(":");return{taskId:taskId.trim(),answer:rest.join(":").trim()}})}}))}/></label><h3>피드백 문장 틀</h3><label>잘한 점<Lines value={result.feedbackTemplates.strengths} onChange={v=>edit(x=>({...x,feedbackTemplates:{...x.feedbackTemplates,strengths:v}}))}/></label><label>다음 학습 방향<Lines value={result.feedbackTemplates.nextSteps} onChange={v=>edit(x=>({...x,feedbackTemplates:{...x.feedbackTemplates,nextSteps:v}}))}/></label></section>;
}
function RubricEditor({criterion,onChange}:{criterion:RubricCriterion;onChange:(x:RubricCriterion)=>void}){return <article className="pa-rubric-edit"><header><b>{criterion.criterionId} · {criterion.assessmentElement}</b><span>{criterion.maxScore?`${criterion.maxScore}점`:"성취수준"}</span></header><label>관찰 근거<textarea value={criterion.observableEvidence} onChange={e=>onChange({...criterion,observableEvidence:e.target.value})}/></label>{criterion.levels.map((level,i)=><div key={i}><input value={level.levelName} onChange={e=>onChange({...criterion,levels:criterion.levels.map((x,n)=>n===i?{...x,levelName:e.target.value}:x)})}/><textarea value={level.description} onChange={e=>onChange({...criterion,levels:criterion.levels.map((x,n)=>n===i?{...x,description:e.target.value}:x)})}/>{criterion.maxScore>0&&<input type="number" min="0" max={criterion.maxScore} value={level.score} onChange={e=>onChange({...criterion,levels:criterion.levels.map((x,n)=>n===i?{...x,score:Number(e.target.value)}:x)})}/>}</div>)}</article>}
function PrintPreview({result,input,tab}:{result:PerformanceAssessment;input:PerformanceAssessmentInput;tab:Tab}){const view=tab==="teacher"?"teacher":tab==="rubric"||tab==="checklist"?"rubric":"student";return <div className={`pa-print-root pa-preview-${view}`}><StudentPrint result={result}/><TeacherPrint result={result}/><RubricPrint result={result} input={input}/></div>}
function StudentPrint({result}:{result:PerformanceAssessment}){return <article className="pa-sheet pa-student-print"><header><h1>{result.title}</h1><div><span>학년·반 __________</span><span>이름 __________</span><span>날짜 __________</span></div></header><p className="pa-student-intro">{result.studentWorksheet.introduction}</p>{result.studentWorksheet.sourceText&&<blockquote>{result.studentWorksheet.sourceText}</blockquote>}<ol>{result.studentWorksheet.tasks.map(task=><li key={task.id}><b>{task.instruction}</b>{Array.from({length:task.answerSpaceLines},(_,i)=><div className="pa-answer-line" key={i}/>)}</li>)}</ol>{result.studentWorksheet.selfAssessment.length>0&&<section className="pa-self"><h2>내가 확인해요</h2>{result.studentWorksheet.selfAssessment.map(x=><p key={x}>□ {x}　😊　😐　😕</p>)}</section>}</article>}
function TeacherPrint({result}:{result:PerformanceAssessment}){return <article className="pa-sheet pa-teacher-print"><header><h1>{result.title} · 교사용 평가계획</h1><p>교사가 사실을 확인하고 수정하여 사용하는 초안입니다.</p></header><table><tbody><tr><th>학년·교과</th><td>1학년 국어</td><th>영역</th><td>{result.overview.domain}</td></tr><tr><th>성취기준</th><td colSpan={3}>{result.overview.achievementStandard}</td></tr><tr><th>평가 요소</th><td colSpan={3}>{result.overview.assessmentElements.join(", ")}</td></tr><tr><th>방법·시기</th><td>{result.overview.assessmentMethods.join(", ")} · {result.overview.timing}</td><th>시간</th><td>{result.overview.duration}분</td></tr></tbody></table><Section title="평가 의도" items={[result.teacherGuide.intent]}/><Section title="준비물" items={result.overview.materials}/><Section title="교사 진행 절차" items={result.teacherGuide.procedure}/><Section title="관찰할 행동" items={result.teacherGuide.observableBehaviors}/><Section title="도움이 필요한 학생 지원" items={result.teacherGuide.support}/><Section title="유의사항" items={result.teacherGuide.cautions}/><Section title="예시·허용 가능한 답" items={result.teacherGuide.sampleAnswers.map(x=>`${x.taskId}: ${x.answer}`)}/><Section title="피드백 문장 예시" items={[...result.feedbackTemplates.strengths,...result.feedbackTemplates.nextSteps,...result.feedbackTemplates.practice]}/></article>}
function RubricPrint({result,input}:{result:PerformanceAssessment;input:PerformanceAssessmentInput}){return <article className="pa-sheet pa-rubric-print"><header><h1>{result.title} · 채점기준 및 관찰표</h1></header><table className="pa-rubric-table"><thead><tr><th>평가 요소</th>{input.levelNames.map(x=><th key={x}>{x}</th>)}<th>관찰 근거</th></tr></thead><tbody>{result.rubric.map(x=><tr key={x.criterionId}><th>{x.assessmentElement}{x.maxScore>0&&<small>{x.maxScore}점</small>}</th>{x.levels.map(l=><td key={l.levelName}>{l.description}{x.maxScore>0&&<b>{l.score}점</b>}</td>)}<td>{x.observableEvidence}</td></tr>)}</tbody></table><h2>관찰 체크리스트</h2><table><thead><tr><th>학생 이름</th>{result.observationChecklist.map((x,i)=><th key={i}>{x.observableBehavior}</th>)}<th>관찰 메모</th><th>최종 성취수준</th></tr></thead><tbody>{Array.from({length:8},(_,i)=><tr key={i}><td>　</td>{result.observationChecklist.map((_,n)=><td key={n}>□</td>)}<td/><td/></tr>)}</tbody></table></article>}
function Section({title,items}:{title:string;items:string[]}){return <section className="pa-print-section"><h2>{title}</h2><ul>{items.map((x,i)=><li key={`${x}-${i}`}>{x}</li>)}</ul></section>}
