"use client";

import { useState } from "react";
import { AlertCircle, Check, ClipboardList, Copy, LoaderCircle, RefreshCw, Sparkles } from "lucide-react";
import { FieldError } from "./generator-result";
import { SEMESTERS, STUDENT_LEVELS, validateLessonPlanInput, type LessonPlanData, type LessonPlanErrors, type LessonPlanInput } from "../lib/lesson-plan-generator";
import { LESSON_TYPES } from "../lib/lesson-plan-reference";

type Overview = { grade:string; subject:string; semester:string; unit:string; topic:string; session:string; textbook:string; achievementStandard:string };
type Result = LessonPlanData & { overview: Overview };
const initialForm: LessonPlanInput = { grade:"1학년", subject:"국어", semester:"1학기", unit:"", topic:"", achievementStandard:"", currentSession:1, totalSessions:1, durationMinutes:40, studentLevel:"수준 혼합", lessonType:"자동 선택", textbookName:"", textbookPages:"", coreContent:"", classCharacteristics:"", desiredActivities:"", availableMaterials:"", additionalRequests:"" };

const lines = (value:string) => value.split("\n").map(x=>x.trim()).filter(Boolean);
const text = (value:string[]) => value.join("\n");

export function LessonPlanGenerator() {
  const [form,setForm]=useState<LessonPlanInput>(initialForm); const [errors,setErrors]=useState<LessonPlanErrors>({});
  const [result,setResult]=useState<Result|null>(null); const [isLoading,setIsLoading]=useState(false); const [apiError,setApiError]=useState(""); const [copied,setCopied]=useState(false);
  const update=<K extends keyof LessonPlanInput>(key:K,value:LessonPlanInput[K])=>{setForm(c=>({...c,[key]:value}));setErrors(c=>({...c,[key]:undefined}));};
  const generate=async()=>{const v=validateLessonPlanInput(form);setErrors(v.errors);setApiError("");setCopied(false);if(!v.data)return;setIsLoading(true);try{const response=await fetch("/api/lesson-plans/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(v.data)});const payload=await response.json() as {plan?:LessonPlanData;overview?:Overview;error?:string;fields?:LessonPlanErrors};if(!response.ok||!payload.plan||!payload.overview){if(payload.fields)setErrors(payload.fields);throw new Error(payload.error||"지도안을 생성하지 못했습니다.");}setResult({...payload.plan,overview:payload.overview});}catch(error){setApiError(error instanceof Error?error.message:"지도안을 생성하지 못했습니다. 잠시 후 다시 시도해 주세요.");}finally{setIsLoading(false);}};
  const setOverview=(key:keyof Overview,value:string)=>setResult(c=>c?{...c,overview:{...c.overview,[key]:value}}:c);
  const setArray=(key:"learningObjectives"|"teacherMaterials"|"studentMaterials",value:string)=>setResult(c=>c?{...c,[key]:lines(value)}:c);
  const setStage=(index:number,key:keyof LessonPlanData["lessonStages"][number],value:string|number)=>setResult(c=>{if(!c)return c;const lessonStages=[...c.lessonStages];const arrayKey=key==="teacherActivities"||key==="studentActivities"||key==="materialsAndNotes";lessonStages[index]={...lessonStages[index],[key]:arrayKey&&typeof value==="string"?lines(value):value} as LessonPlanData["lessonStages"][number];return{...c,lessonStages};});
  const setAssessment=(key:"content"|"method"|"observableBehaviors",value:string)=>setResult(c=>c?{...c,assessment:{...c.assessment,[key]:lines(value)}}:c);
  const setCriterion=(key:keyof LessonPlanData["assessment"]["criteria"],value:string)=>setResult(c=>c?{...c,assessment:{...c.assessment,criteria:{...c.assessment.criteria,[key]:value}}}:c);
  const setSupport=(index:number,value:string)=>setResult(c=>{if(!c)return c;const levelSupport=[...c.levelSupport];levelSupport[index]={...levelSupport[index],support:lines(value)};return{...c,levelSupport};});
  const copyAll=async()=>{if(!result)return;const out=[result.title,`교과: ${result.overview.subject}`,`학년: ${result.overview.grade}`,`학기: ${result.overview.semester}`,`단원: ${result.overview.unit}`,`차시 주제: ${result.overview.topic}`,`차시: ${result.overview.session}`,`교과서: ${result.overview.textbook}`,`수업 유형: ${result.lessonType}`,`성취기준: ${result.overview.achievementStandard}`,"\n[학습 목표]",...result.learningObjectives.map(x=>`- ${x}`),"\n[준비물]","교사: "+result.teacherMaterials.join(", "),"학생: "+result.studentMaterials.join(", "),"\n[수업 흐름]",...result.lessonStages.flatMap(s=>[`${s.stage} · ${s.learningContent} (${s.minutes}분)`,`교사 활동: ${s.teacherActivities.join(" / ")}`,`학생 활동: ${s.studentActivities.join(" / ")}`,`자료 및 유의점: ${s.materialsAndNotes.join(" / ")}`]),"\n[평가 계획]","평가 내용: "+result.assessment.content.join(" / "),"평가 방법: "+result.assessment.method.join(" / "),"관찰 행동: "+result.assessment.observableBehaviors.join(" / "),`상: ${result.assessment.criteria.high}`,`중: ${result.assessment.criteria.medium}`,`하: ${result.assessment.criteria.low}`,`목표-활동-평가 연결: ${result.assessment.alignmentEvidence}`,"\n[수준별 지원]",...result.levelSupport.map(x=>`${x.level}: ${x.support.join(" / ")}`)].join("\n");try{await navigator.clipboard.writeText(out);setCopied(true);window.setTimeout(()=>setCopied(false),2000);}catch{setApiError("복사하지 못했습니다. 각 내용을 직접 선택해 복사해 주세요.");}};

  return <><div className="page-title message-page-title"><div><span className="eyebrow">LESSON PLAN ASSISTANT · 1학년 국어</span><h1>1학년 국어 지도안 생성기</h1><p>참고자료의 수업 설계 원리에 따라 목표·활동·평가가 연결된 지도안을 작성해 드려요.</p></div><span className="privacy-note"><Check size={15}/> 입력 내용은 저장하지 않아요</span></div>
  <div className="lesson-plan-layout"><section className="form-panel message-form lesson-plan-form"><div className="panel-head"><div><span className="eyebrow">STEP 1</span><h3>기본 수업 정보</h3></div><span className="required">* 필수 항목</span></div>
    <div className="kw-fixed"><b>초등학교</b><b>1학년</b><b>국어</b></div>
    <div className="field-row"><label>학기 *<select value={form.semester} onChange={e=>update("semester",e.target.value as LessonPlanInput["semester"])}>{SEMESTERS.map(x=><option key={x}>{x}</option>)}</select><FieldError message={errors.semester}/></label><label>수업 유형 *<select value={form.lessonType} onChange={e=>update("lessonType",e.target.value as LessonPlanInput["lessonType"])}>{LESSON_TYPES.map(x=><option key={x}>{x}</option>)}</select><FieldError message={errors.lessonType}/></label></div>
    <label>단원명 *<input value={form.unit} placeholder="예: 2. 받침이 있는 글자를 읽어요" onChange={e=>update("unit",e.target.value)}/><FieldError message={errors.unit}/></label>
    <label>차시 주제 *<input value={form.topic} placeholder="예: 받침이 있는 글자의 짜임 알아보기" onChange={e=>update("topic",e.target.value)}/><FieldError message={errors.topic}/></label>
    <label>성취기준 *<small className="field-help">교육과정에 제시된 문구를 그대로 입력해 주세요.</small><textarea value={form.achievementStandard} placeholder="성취기준 코드와 문구를 그대로 입력해 주세요." onChange={e=>update("achievementStandard",e.target.value)}/><FieldError message={errors.achievementStandard}/></label>
    <div className="field-row lesson-numbers"><label>현재 차시 *<input type="number" min="1" step="1" value={form.currentSession} onChange={e=>update("currentSession",Number(e.target.value))}/><FieldError message={errors.currentSession}/></label><label>전체 차시 *<input type="number" min="1" step="1" value={form.totalSessions} onChange={e=>update("totalSessions",Number(e.target.value))}/><FieldError message={errors.totalSessions}/></label></div>
    <label>수업 시간(분) *<input type="number" min="1" step="1" value={form.durationMinutes} onChange={e=>update("durationMinutes",Number(e.target.value))}/><FieldError message={errors.durationMinutes}/></label><div className="field-row"><label>교과서명 <span className="optional">선택</span><input value={form.textbookName||""} placeholder="입력한 경우에만 결과에 사용" onChange={e=>update("textbookName",e.target.value)}/></label><label>교과서 쪽수 <span className="optional">선택</span><input value={form.textbookPages||""} placeholder="예: 20~23쪽" onChange={e=>update("textbookPages",e.target.value)}/></label></div>
    <fieldset><legend>학생 수준 *</legend><div className="choice-grid four">{STUDENT_LEVELS.map(x=><button type="button" key={x} className={form.studentLevel===x?"choice active":"choice"} onClick={()=>update("studentLevel",x)}>{x}</button>)}</div><FieldError message={errors.studentLevel}/></fieldset>
    <div className="divider"/><div className="panel-head option-head"><div><span className="eyebrow">STEP 2</span><h3>추가 수업 정보</h3></div></div>
    <label>이번 차시의 핵심 내용 <span className="optional">선택</span><textarea value={form.coreContent} placeholder="이번 시간에 학생들이 꼭 이해하거나 할 수 있어야 하는 내용을 적어 주세요." onChange={e=>update("coreContent",e.target.value)}/></label>
    <label>학급 또는 학생의 특성 <span className="optional">선택</span><small className="field-help privacy-warning">학생 실명, 건강 정보 등 민감한 개인정보는 입력하지 마세요.</small><textarea value={form.classCharacteristics} placeholder="예: 발표 참여도에 차이가 크고 모둠 활동 경험이 적음" onChange={e=>update("classCharacteristics",e.target.value)}/></label>
    <label>포함하고 싶은 활동 <span className="optional">선택</span><textarea value={form.desiredActivities} placeholder="예: 짝 토의, 생각 그물 만들기" onChange={e=>update("desiredActivities",e.target.value)}/></label>
    <label>사용 가능한 준비물이나 자료 <span className="optional">선택</span><textarea value={form.availableMaterials} placeholder="예: 포스트잇, 색연필, 모둠별 도화지" onChange={e=>update("availableMaterials",e.target.value)}/></label>
    <label>교사의 추가 요청 <span className="optional">선택</span><textarea value={form.additionalRequests} placeholder="예: 전개 단계에서 개별 활동 시간을 충분히 확보해 주세요." onChange={e=>update("additionalRequests",e.target.value)}/></label>
    <button type="button" className="primary-btn generate-message" onClick={generate} disabled={isLoading}>{isLoading?<><LoaderCircle className="spin" size={17}/> 지도안을 작성하고 있어요</>:<><Sparkles size={17}/> 지도안 생성</>}</button>
  </section>
  <section className="lesson-result" aria-live="polite"><div className="panel-head"><div><span className="eyebrow"><ClipboardList size={13}/> 생성 결과</span><h3>수업 지도안</h3></div>{result&&<span className="result-ready"><Check size={13}/> 항목별 수정 가능</span>}</div>{apiError&&<div className="api-error"><AlertCircle size={19}/><div><b>지도안을 생성하지 못했어요</b><p>{apiError}</p><span>입력값과 수업 시간을 확인한 뒤 다시 생성해 주세요.</span></div></div>}
    {!result?<div className="message-empty lesson-empty"><span><ClipboardList size={28}/></span><b>아직 생성된 지도안이 없어요</b><p>왼쪽에서 수업 정보를 입력한 뒤<br/>지도안 생성 버튼을 눌러 주세요.</p><div><span>1</span>수업 정보<span>2</span>AI 생성<span>3</span>항목 수정</div></div>:<div className="lesson-document">
      <input className="lesson-title-input" value={result.title} onChange={e=>setResult(c=>c?{...c,title:e.target.value}:c)} aria-label="지도안 제목"/>
      <LessonSection title="1. 수업 개요"><div className="overview-grid">{(["subject","grade","semester","unit","topic","session","textbook","achievementStandard"] as const).map(key=><label key={key}><span>{{subject:"교과",grade:"학년",semester:"학기",unit:"단원",topic:"차시 주제",session:"차시",textbook:"교과서·쪽수",achievementStandard:"성취기준"}[key]}</span><textarea value={result.overview[key]} onChange={e=>setOverview(key,e.target.value)}/></label>)}</div><p className="lesson-type-note">수업 유형: <b>{result.lessonType}</b></p></LessonSection>
      <LessonSection title="2. 학습 목표"><textarea className="section-editor" value={text(result.learningObjectives)} onChange={e=>setArray("learningObjectives",e.target.value)}/></LessonSection>
      <LessonSection title="3. 준비물"><div className="field-row"><label>교사 준비물<textarea value={text(result.teacherMaterials)} onChange={e=>setArray("teacherMaterials",e.target.value)}/></label><label>학생 준비물<textarea value={text(result.studentMaterials)} onChange={e=>setArray("studentMaterials",e.target.value)}/></label></div></LessonSection>
      <LessonSection title="4. 수업 흐름"><div className="lesson-stage-table"><div className="stage-header"><span>단계·시간</span><span>학습 내용</span><span>교사 활동</span><span>학생 활동</span><span>자료 및 유의점</span></div>{result.lessonStages.map((s,i)=><div className="stage-row" key={s.stage}><div className="stage-name"><b>{s.stage}</b><label><input type="number" min="1" value={s.minutes} onChange={e=>setStage(i,"minutes",Number(e.target.value))}/>분</label></div><label data-label="학습 내용"><textarea value={s.learningContent} onChange={e=>setStage(i,"learningContent",e.target.value)}/></label><label data-label="교사 활동"><textarea value={text(s.teacherActivities)} onChange={e=>setStage(i,"teacherActivities",e.target.value)}/></label><label data-label="학생 활동"><textarea value={text(s.studentActivities)} onChange={e=>setStage(i,"studentActivities",e.target.value)}/></label><label data-label="자료 및 유의점"><textarea value={text(s.materialsAndNotes)} onChange={e=>setStage(i,"materialsAndNotes",e.target.value)}/></label></div>)}</div><p className="time-total">현재 배정 시간 합계: <b>{result.lessonStages.reduce((a,b)=>a+b.minutes,0)}분</b> · 입력 수업 시간: {form.durationMinutes}분</p></LessonSection>
      <LessonSection title="5. 평가 계획"><div className="assessment-grid">{(["content","method","observableBehaviors"] as const).map(key=><label key={key}><span>{{content:"평가 내용",method:"평가 방법",observableBehaviors:"관찰할 학생 행동"}[key]}</span><textarea value={text(result.assessment[key])} onChange={e=>setAssessment(key,e.target.value)}/></label>)}</div><div className="criteria-grid">{(["high","medium","low"] as const).map(key=><label key={key}><span>{{high:"상",medium:"중",low:"하"}[key]} 기준</span><textarea value={result.assessment.criteria[key]} onChange={e=>setCriterion(key,e.target.value)}/></label>)}</div><label className="alignment-editor"><span>목표·활동·평가 연결 근거</span><textarea value={result.assessment.alignmentEvidence} onChange={e=>setResult(c=>c?{...c,assessment:{...c.assessment,alignmentEvidence:e.target.value}}:c)}/></label></LessonSection>
      <LessonSection title="6. 수준별 지원"><div className="support-grid">{result.levelSupport.map((s,i)=><label key={s.level}><span className={`level-badge level-${s.level}`}>{s.level}</span><textarea value={text(s.support)} onChange={e=>setSupport(i,e.target.value)}/></label>)}</div></LessonSection>
      <p className="edit-hint">수업 전에 학급 상황에 맞게 시간과 활동 내용을 검토해 주세요.</p><div className="preview-actions message-actions"><button className="ghost-btn" onClick={copyAll}>{copied?<><Check size={16}/> 복사 완료</>:<><Copy size={16}/> 전체 내용 복사</>}</button><button className="primary-btn" onClick={generate} disabled={isLoading}>{isLoading?<LoaderCircle className="spin" size={16}/>:<RefreshCw size={16}/>} 다시 생성</button></div>
    </div>}
  </section></div></>;
}

function LessonSection({title,children}:{title:string;children:React.ReactNode}) { return <section className="lesson-section"><h4>{title}</h4>{children}</section>; }
