/* eslint-disable @typescript-eslint/no-unused-expressions */
"use client";
import { useState } from "react";
import { AlertCircle,ArrowDown,ArrowUp,Check,LoaderCircle,Lock,Printer,RefreshCw,Sparkles,Trash2,Unlock } from "lucide-react";
import { FieldError } from "./generator-result";
import { KOREAN_WORKSHEET_AREAS,KOREAN_WORKSHEET_LEVELS,type KoreanWorksheetArea,type KoreanWorksheetLevel } from "../lib/korean-worksheet-config";
import { combineWorksheetSets,printableWorksheetIssues,validateKoreanWorksheetInput,type KoreanWorksheetErrors,type KoreanWorksheetInput,type LevelWorksheet,type WorksheetItem,type WorksheetSet } from "../lib/leveled-korean-worksheet";

const initial:KoreanWorksheetInput={semester:"학기 구분 없이",unit:"",lesson:"",achievementStandard:"",learningGoal:"",coreContent:"",keywords:"",sourceText:"",desiredActivities:"",additionalRequest:"",areas:["낱말 읽기"],levels:[...KOREAN_WORKSHEET_LEVELS],itemCount:5,pages:1,composition:"선택형·쓰기 활동 혼합",fontSize:"크게",spacing:"넓게"};
const steps=["학습 정보 입력","활동지 설정","수준별 생성","내용 확인·수정","학생용·교사용 미리보기","인쇄"];

export function LeveledKoreanWorksheetGenerator(){
 const[form,setForm]=useState(initial),[errors,setErrors]=useState<KoreanWorksheetErrors>({}),[result,setResult]=useState<WorksheetSet|null>(null),[loading,setLoading]=useState(false),[apiError,setApiError]=useState(""),[failed,setFailed]=useState<KoreanWorksheetLevel[]>([]),[active,setActive]=useState<KoreanWorksheetLevel>("보충"),[mode,setMode]=useState<"edit"|"student"|"teacher">("edit"),[locked,setLocked]=useState<Set<string>>(new Set()),[busyLevel,setBusyLevel]=useState<KoreanWorksheetLevel|null>(null);
 const current=loading?3:result?(mode==="edit"?4:5):1;const selectedLevel=result?.levels.find(x=>x.level===active)||result?.levels[0];
 const update=<K extends keyof KoreanWorksheetInput>(key:K,value:KoreanWorksheetInput[K])=>{setForm(c=>({...c,[key]:value}));setErrors(c=>({...c,[key]:undefined}))};
 const toggleArea=(area:KoreanWorksheetArea)=>update("areas",form.areas.includes(area)?form.areas.filter(x=>x!==area):[...form.areas,area]);
 const requestLevel=async(level:KoreanWorksheetLevel,excludePrompts:string[]=[])=>{const response=await fetch("/api/leveled-korean-worksheets/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({input:{...form,levels:[level]},level,excludePrompts})});const payload=await response.json() as {worksheet?:WorksheetSet;error?:string};if(!response.ok||!payload.worksheet)throw new Error(payload.error||`${level} 활동지를 생성하지 못했습니다.`);return payload.worksheet};
 const requestWithRetry=async(level:KoreanWorksheetLevel,exclude:string[]=[])=>{try{return await requestLevel(level,exclude)}catch{return requestLevel(level,exclude)}};
 const generate=async()=>{const v=validateKoreanWorksheetInput(form);setErrors(v.errors);setApiError("");setFailed([]);if(!v.data)return;setLoading(true);try{const settled=await Promise.allSettled(form.levels.map(level=>requestWithRetry(level)));const good=settled.flatMap(x=>x.status==="fulfilled"?[x.value]:[]);const bad=form.levels.filter((_,i)=>settled[i].status==="rejected");setFailed(bad);if(!good.length)throw new Error("활동지를 생성하지 못했습니다. 입력 내용을 확인하고 다시 시도해 주세요.");setResult(combineWorksheetSets(good,form));setActive(good[0].levels[0].level);setMode("edit");setLocked(new Set());if(bad.length)setApiError(`${bad.join("·")} 활동지만 생성되지 않았습니다. 실패한 수준 다시 생성을 눌러 주세요.`)}catch(error){setApiError(error instanceof Error?error.message:"활동지를 생성하지 못했습니다.")}finally{setLoading(false)}};
 const replaceLevel=(next:LevelWorksheet,guide:WorksheetSet["teacherGuide"])=>setResult(c=>c?{...c,levels:[...c.levels.filter(x=>x.level!==next.level),next].sort((a,b)=>KOREAN_WORKSHEET_LEVELS.indexOf(a.level)-KOREAN_WORKSHEET_LEVELS.indexOf(b.level)),teacherGuide:{...c.teacherGuide,levelDifferences:[...c.teacherGuide.levelDifferences,...guide.levelDifferences],teachingTips:[...new Set([...c.teacherGuide.teachingTips,...guide.teachingTips])],answerKey:[...c.teacherGuide.answerKey.filter(x=>x.level!==next.level),...guide.answerKey]}}:c);
 const regenerateLevel=async(level:KoreanWorksheetLevel,keepLocked=false)=>{if(!result)return;setBusyLevel(level);setApiError("");try{const old=result.levels.find(x=>x.level===level);const part=await requestWithRetry(level,old?.items.map(x=>x.prompt)||[]);let next=part.levels[0];if(keepLocked&&old){next={...next,studentTitle:old.studentTitle,items:next.items.map((item,i)=>locked.has(old.items[i]?.id)?old.items[i]:item)};part.teacherGuide.answerKey=next.items.map(item=>({level,itemId:item.id,answer:item.correctAnswer,acceptedAnswers:item.acceptedAnswers,explanation:item.explanation}))}replaceLevel(next,part.teacherGuide);setFailed(c=>c.filter(x=>x!==level))}catch(error){setApiError(error instanceof Error?error.message:`${level} 활동지를 다시 생성하지 못했습니다.`)}finally{setBusyLevel(null)}};
 const regenerateItem=async(index:number)=>{if(!selectedLevel)return;setBusyLevel(selectedLevel.level);try{const part=await requestWithRetry(selectedLevel.level,selectedLevel.items.map(x=>x.prompt));const item=part.levels[0].items[0];editLevel(level=>({...level,items:level.items.map((x,i)=>i===index?{...item,id:x.id}:x)}))}catch(error){setApiError(error instanceof Error?error.message:"문항을 다시 생성하지 못했습니다.")}finally{setBusyLevel(null)}};
 const editLevel=(fn:(level:LevelWorksheet)=>LevelWorksheet)=>setResult(c=>c?{...c,levels:c.levels.map(level=>level.level===active?fn(level):level)}:c);
 const editItem=(index:number,key:keyof WorksheetItem,value:string|number|string[])=>editLevel(level=>({...level,items:level.items.map((item,i)=>i===index?{...item,[key]:value}:item)}));
 const move=(index:number,by:number)=>editLevel(level=>{const items=[...level.items],to=index+by;if(to<0||to>=items.length)return level;[items[index],items[to]]=[items[to],items[index]];return{...level,items}});
 const print=(target:"selected"|"all"|"teacher"|"both")=>{if(!result)return;const issues=printableWorksheetIssues(result);if(issues.length){setApiError(`인쇄 전에 확인해 주세요: ${issues[0]}`);return}document.documentElement.dataset.kwPrint=target;document.documentElement.dataset.kwLevel=active;window.addEventListener("afterprint",()=>{delete document.documentElement.dataset.kwPrint;delete document.documentElement.dataset.kwLevel},{once:true});window.print()};
 return <div className="kw-page"><header className="page-head"><div><span className="eyebrow">수업 도우미 · 국어</span><h1>1학년 국어 수준별 활동지 생성기</h1><p>하나의 학습 목표를 보충·기본·심화의 서로 다른 도움과 사고 수준으로 구성해요.</p></div><span className="privacy-note"><Check size={15}/> 제시문과 결과는 저장하지 않아요</span></header>
  <nav className="kw-steps" aria-label="활동지 생성 단계">{steps.map((x,i)=><span className={i+1===current?"current":i+1<current?"done":""} key={x}><b>{i+1}</b>{x}</span>)}</nav>
  <div className="kw-layout"><aside className="kw-controls"><section className="dm-card"><h2><span>1</span> 학습 정보</h2><div className="kw-fixed"><b>초등학교</b><b>1학년</b><b>국어</b></div><div className="dm-form-grid"><Select label="학기" value={form.semester} onChange={v=>update("semester",v as KoreanWorksheetInput["semester"])}><option>1학기</option><option>2학기</option><option>학기 구분 없이</option></Select><Text label="단원명" optional value={form.unit||""} onChange={v=>update("unit",v)} placeholder="예: 글자를 만들어요"/><Text label="차시" optional value={form.lesson||""} onChange={v=>update("lesson",v)} placeholder="예: 3차시"/></div><TextArea label="성취기준" optional value={form.achievementStandard||""} onChange={v=>update("achievementStandard",v)} placeholder="입력한 문구는 그대로 사용합니다."/><TextArea label="학습 목표 *" value={form.learningGoal} onChange={v=>update("learningGoal",v)} placeholder="예: 받침이 있는 낱말을 소리 내어 읽을 수 있다." error={errors.learningGoal}/><TextArea label="학습 주제 또는 핵심 내용 *" value={form.coreContent} onChange={v=>update("coreContent",v)} placeholder="이번 활동에서 꼭 익힐 내용을 적어 주세요." error={errors.coreContent}/><Text label="핵심 낱말" optional value={form.keywords||""} onChange={v=>update("keywords",v)} placeholder="예: 산, 문, 달, 공"/><TextArea label="제시문 또는 학습 자료" optional value={form.sourceText||""} onChange={v=>update("sourceText",v)} placeholder="입력한 글은 학습 자료로만 취급합니다."/><fieldset><legend>1학년 국어 학습 영역 *</legend><div className="kw-area-grid">{KOREAN_WORKSHEET_AREAS.map(x=><button type="button" aria-pressed={form.areas.includes(x)} className={form.areas.includes(x)?"selected":""} onClick={()=>toggleArea(x)} key={x}>{x}</button>)}</div><FieldError message={errors.areas}/></fieldset><Text label="포함하고 싶은 활동" optional value={form.desiredActivities||""} onChange={v=>update("desiredActivities",v)} placeholder="예: 낱말 따라 쓰기, 문장 빈칸 채우기"/><TextArea label="교사의 추가 요청" optional value={form.additionalRequest||""} onChange={v=>update("additionalRequest",v)} placeholder="수업 상황에 필요한 요청을 적어 주세요."/></section>
  <section className="dm-card"><h2><span>2</span> 활동지 설정</h2><label className="dm-field"><span>생성 수준</span><div className="kw-level-options"><button className={form.levels.length===3?"selected":""} onClick={()=>update("levels",[...KOREAN_WORKSHEET_LEVELS])}>세 수준 모두</button>{KOREAN_WORKSHEET_LEVELS.map(x=><button className={form.levels.length===1&&form.levels[0]===x?"selected":""} onClick={()=>update("levels",[x])} key={x}>{x}만</button>)}</div></label><div className="dm-form-grid"><Select label="수준별 문제 수" value={form.itemCount} onChange={v=>update("itemCount",Number(v) as KoreanWorksheetInput["itemCount"])}>{[3,5,7,10].map(x=><option value={x} key={x}>{x}문제</option>)}</Select><Select label="활동지 분량" value={form.pages} onChange={v=>update("pages",Number(v) as 1|2)}><option value={1}>수준별 A4 1쪽</option><option value={2}>수준별 A4 2쪽</option></Select><Select label="문제 구성" value={form.composition} onChange={v=>update("composition",v as KoreanWorksheetInput["composition"])}><option>선택형 중심</option><option>쓰기 활동 중심</option><option>선택형·쓰기 활동 혼합</option></Select><Select label="글자 크기" value={form.fontSize} onChange={v=>update("fontSize",v as "크게"|"보통")}><option>크게</option><option>보통</option></Select><Select label="문제 사이 간격" value={form.spacing} onChange={v=>update("spacing",v as "넓게"|"보통")}><option>넓게</option><option>보통</option></Select></div><button className="primary-btn full kw-generate" disabled={loading} onClick={generate}>{loading?<><LoaderCircle className="spin"/> 수준별 활동지를 만들고 있어요</>:<><Sparkles/> 수준별 활동지 생성</>}</button>{apiError&&<div className="kw-error"><AlertCircle/>{apiError}</div>}{failed.length>0&&<div className="kw-failed">{failed.map(x=><button key={x} onClick={()=>regenerateLevel(x)}>↻ {x} 다시 생성</button>)}</div>}</section></aside>
  <main className="kw-workspace">{!result?<div className="dm-empty"><span><Sparkles/></span><h2>1학년 국어 활동지를 만들어 보세요</h2><p>학습 목표와 핵심 내용을 입력하면<br/>선택한 수준별 활동지와 교사용 자료가 나타납니다.</p></div>:<><div className="kw-toolbar"><div className="dm-segment"><button className={mode==="edit"?"selected":""} onClick={()=>setMode("edit")}>내용 수정</button><button className={mode==="student"?"selected":""} onClick={()=>setMode("student")}>학생용 미리보기</button><button className={mode==="teacher"?"selected":""} onClick={()=>setMode("teacher")}>교사용 자료</button></div><div className="kw-print-buttons"><button onClick={()=>print("selected")}><Printer/>선택 수준 인쇄</button><button onClick={()=>print("all")}><Printer/>세 수준 인쇄</button><button onClick={()=>print("teacher")}>교사용 인쇄</button><button onClick={()=>print("both")}>학생용·교사용 모두</button></div></div><div className="kw-level-tabs">{result.levels.map(x=><button className={active===x.level?"active":""} onClick={()=>setActive(x.level)} key={x.level}>{x.level}<small>{x.studentTitle}</small></button>)}</div>{mode==="edit"&&selectedLevel&&<WorksheetEditor level={selectedLevel} locked={locked} setLocked={setLocked} editLevel={editLevel} editItem={editItem} move={move} regenerateItem={regenerateItem} regenerateLevel={regenerateLevel} busy={busyLevel===selectedLevel.level}/>}<div className={`kw-print-root kw-font-${form.fontSize} kw-space-${form.spacing}`}><div className={mode==="student"?"":"kw-screen-hidden"}><StudentSheets set={result} levels={result.levels} active={active} pages={form.pages}/></div><div className={mode==="teacher"?"":"kw-screen-hidden"}><TeacherSheets set={result}/></div></div></>}</main></div></div>;
}

function Select({label,value,onChange,children}:{label:string;value:string|number;onChange:(v:string)=>void;children:React.ReactNode}){return <label className="dm-field"><span>{label}</span><select value={value} onChange={e=>onChange(e.target.value)}>{children}</select></label>}
function Text({label,value,onChange,placeholder,optional}:{label:string;value:string;onChange:(v:string)=>void;placeholder?:string;optional?:boolean}){return <label className="dm-field"><span>{label}{optional&&<small> 선택</small>}</span><input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></label>}
function TextArea({label,value,onChange,placeholder,optional,error}:{label:string;value:string;onChange:(v:string)=>void;placeholder?:string;optional?:boolean;error?:string}){return <label className="dm-field"><span>{label}{optional&&<small> 선택</small>}</span><textarea value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/><FieldError message={error}/></label>}
function WorksheetEditor({level,locked,setLocked,editLevel,editItem,move,regenerateItem,regenerateLevel,busy}:{level:LevelWorksheet;locked:Set<string>;setLocked:(v:Set<string>)=>void;editLevel:(fn:(x:LevelWorksheet)=>LevelWorksheet)=>void;editItem:(i:number,k:keyof WorksheetItem,v:string|number|string[])=>void;move:(i:number,b:number)=>void;regenerateItem:(i:number)=>void;regenerateLevel:(l:KoreanWorksheetLevel,keep?:boolean)=>void;busy:boolean}){const toggle=(id:string)=>{const next=new Set(locked);next.has(id)?next.delete(id):next.add(id);setLocked(next)};return <section className="kw-editor"><div className="kw-editor-head"><label>학생용 제목<input value={level.studentTitle} onChange={e=>editLevel(x=>({...x,studentTitle:e.target.value}))}/></label><div><button disabled={busy} onClick={()=>regenerateLevel(level.level)}><RefreshCw/>수준 전체 다시</button><button disabled={busy} onClick={()=>regenerateLevel(level.level,true)}><Lock/>고정 제외 다시</button></div></div>{level.items.map((item,i)=><article className="kw-edit-item" key={item.id}><header><b>{i+1}. {item.type}</b><div><button title="위로" onClick={()=>move(i,-1)}><ArrowUp/></button><button title="아래로" onClick={()=>move(i,1)}><ArrowDown/></button><button title={locked.has(item.id)?"고정 해제":"문제 고정"} onClick={()=>toggle(item.id)}>{locked.has(item.id)?<Lock/>:<Unlock/>}</button><button title="이 문제 다시 생성" disabled={busy||locked.has(item.id)} onClick={()=>regenerateItem(i)}><RefreshCw/></button><button title="문제 삭제" onClick={()=>editLevel(x=>({...x,items:x.items.filter((_,n)=>n!==i)}))}><Trash2/></button></div></header><label>문제<textarea value={item.prompt} onChange={e=>editItem(i,"prompt",e.target.value)}/></label><div className="dm-form-grid"><label>보기 <small>줄마다 한 개</small><textarea value={item.options.join("\n")} onChange={e=>editItem(i,"options",e.target.value.split("\n").filter(Boolean))}/></label><label>정답<input value={item.correctAnswer} onChange={e=>editItem(i,"correctAnswer",e.target.value)}/></label><label>도움 또는 예시<textarea value={item.scaffold} onChange={e=>editItem(i,"scaffold",e.target.value)}/></label><label>해설<textarea value={item.explanation} onChange={e=>editItem(i,"explanation",e.target.value)}/></label></div></article>)}</section>}
function StudentSheets({set,levels,active,pages}:{set:WorksheetSet;levels:LevelWorksheet[];active:KoreanWorksheetLevel;pages:number}){return <div className="kw-student-print">{levels.map(level=>{const per=Math.ceil(level.items.length/pages);return Array.from({length:pages},(_,page)=>{const items=level.items.slice(page*per,(page+1)*per);return <article className={`kw-sheet kw-level-${level.level} ${level.level===active?"":"kw-screen-level-hidden"}`} data-level={level.level} key={`${level.level}-${page}`}><header><div><h2>{level.studentTitle}</h2><p>{set.learningGoal}</p></div><div className="kw-student-meta"><span>학년·반 <i/></span><span>이름 <i/></span><span>날짜 <i/></span></div></header><p className="kw-instructions">{level.instructions}</p><section>{items.map((item,i)=><StudentItem item={item} number={page*per+i+1} key={item.id}/>)}</section><footer>{page+1} / {pages}</footer></article>})})}</div>}
function StudentItem({item,number}:{item:WorksheetItem;number:number}){return <article className="kw-item"><h3><span>{number}</span>{item.prompt}</h3>{item.sourceText&&<blockquote>{item.sourceText}</blockquote>}{item.scaffold&&<p className="kw-scaffold">도움: {item.scaffold}</p>}{item.options.length>0&&<div className="kw-options">{item.options.map((x,i)=><span key={`${x}-${i}`}>○ {x}</span>)}</div>}{Array.from({length:Math.max(1,item.writingLines)},(_,i)=><div className="kw-writing-line" key={i}/>)}</article>}
function TeacherSheets({set}:{set:WorksheetSet}){return <div className="kw-teacher-print"><article className="kw-sheet kw-teacher-sheet"><header><div><h2>{set.title} · 교사용 자료</h2><p>공통 학습 목표: {set.teacherGuide.commonLearningGoal}</p></div></header><section className="kw-guide"><h3>수준별 차이</h3><ul>{set.teacherGuide.levelDifferences.map(x=><li key={x}>{x}</li>)}</ul><h3>지도 도움말</h3><ul>{set.teacherGuide.teachingTips.map(x=><li key={x}>{x}</li>)}</ul>{set.levels.map(level=><section key={level.level}><h3>{level.level} · {level.studentTitle}</h3>{level.items.map((item,i)=>{const answer=set.teacherGuide.answerKey.find(x=>x.level===level.level&&x.itemId===item.id);const accepted=item.acceptedAnswers.length?item.acceptedAnswers:answer?.acceptedAnswers||[];return <div className="kw-answer" key={item.id}><b>{i+1}. {item.prompt}</b><p>정답: {item.correctAnswer||answer?.answer||item.sampleAnswer||"예시 답안 참고"}</p>{accepted.length>0&&<p>허용 답안: {accepted.join(", ")}</p>}<p>해설: {item.explanation||answer?.explanation}</p></div>})}</section>)}</section></article></div>}
