"use client";
import {useEffect,useState} from "react";
import {AlertTriangle,Check,ClipboardList,LoaderCircle} from "lucide-react";
import {validatePublicAnswers,type PublicAnswer,type SurveyQuestion} from "../lib/survey";
type PublicSurvey={title:string;description:string;targetType:string;responseMode:"anonymous"|"identified";identityFields:string[];privacyNotice:string;duplicatePolicy:"allow"|"browser_once";status:string;startsAt?:string;endsAt?:string;maxResponses?:number;responseCount?:number;completionMessage:string};
type Payload={error?:string;survey?:PublicSurvey;questions?:SurveyQuestion[]};
export function PublicSurveyForm({slug}:{slug:string}){
 const[survey,setSurvey]=useState<PublicSurvey>(),[questions,setQuestions]=useState<SurveyQuestion[]>([]),[answers,setAnswers]=useState<PublicAnswer[]>([]),[identity,setIdentity]=useState<Record<string,string>>({}),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(""),[fields,setFields]=useState<Record<string,string>>({}),[done,setDone]=useState(false);
 useEffect(()=>{fetch(`/api/public-surveys/${slug}`).then(async r=>{const p=await r.json() as Payload;if(!r.ok)throw new Error(p.error);setSurvey(p.survey);setQuestions(p.questions||[])}).catch(e=>setError(e instanceof Error?e.message:"설문을 불러오지 못했습니다.")).finally(()=>setLoading(false))},[slug]);
 const setAnswer=(questionId:string,patch:Partial<PublicAnswer>)=>setAnswers([...answers.filter(a=>a.questionId!==questionId),{...(answers.find(a=>a.questionId===questionId)||{questionId}),...patch}]);
 const submit=async()=>{const e=validatePublicAnswers(questions,answers);setFields(e);if(Object.keys(e).length)return;setBusy(true);setError("");try{const key=`survey-submitted-${slug}`;if(survey?.duplicatePolicy==="browser_once"&&localStorage.getItem(key)){setError("이 브라우저에서는 이미 응답을 제출했습니다.");return}let token=localStorage.getItem(`survey-token-${slug}`);if(!token){token=crypto.randomUUID();localStorage.setItem(`survey-token-${slug}`,token)}const r=await fetch(`/api/public-surveys/${slug}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token,respondentFields:survey?.responseMode==="identified"?identity:{},answers})});const p=await r.json() as Payload;if(!r.ok)throw new Error(p.error);if(survey?.duplicatePolicy==="browser_once")localStorage.setItem(key,"1");history.replaceState(null,"",location.pathname+"?submitted=1");setDone(true)}catch(e){setError(e instanceof Error?e.message:"응답을 제출하지 못했습니다. 다시 시도해 주세요.")}finally{setBusy(false)}};
 if(loading)return <main className="public-survey"><div className="public-state"><LoaderCircle className="spin"/><h2>설문을 불러오는 중입니다.</h2></div></main>;
 if(error&&!survey)return <main className="public-survey"><div className="public-state"><AlertTriangle/><h2>{error}</h2></div></main>;
 if(!survey)return null;
 if(done)return <main className="public-survey"><div className="public-state success"><Check/><h1>응답이 제출되었습니다</h1><p>{survey.completionMessage}</p></div></main>;
 if(survey.status!=="open")return <main className="public-survey"><div className="public-state"><ClipboardList/><h1>{survey.title}</h1><h2>{survey.status==="scheduled"?"아직 시작하지 않은 설문입니다.":survey.status==="paused"?"현재 응답 접수가 중지되었습니다.":survey.maxResponses!=null&&(survey.responseCount??0)>=survey.maxResponses?`선착순 마감되었습니다. (정원 ${survey.maxResponses}명)`:"마감된 설문입니다."}</h2>{survey.startsAt&&<p>시작: {new Date(survey.startsAt).toLocaleString("ko-KR")}</p>}{survey.endsAt&&<p>종료: {new Date(survey.endsAt).toLocaleString("ko-KR")}</p>}</div></main>;
 return <main className="public-survey"><section className="public-paper"><header><span>온라인 설문</span><h1>{survey.title}</h1><p>{survey.description}</p><div>{survey.targetType} 대상 · 총 {questions.length}문항 {survey.endsAt&&`· ${new Date(survey.endsAt).toLocaleString("ko-KR")} 마감`}{survey.maxResponses!=null&&`· 선착순 ${survey.maxResponses}명 중 ${survey.responseCount??0}명 응답`}</div></header>{survey.responseMode==="identified"&&<section className="identity-box"><h2>응답자 정보</h2><p>{survey.privacyNotice}</p><div>{survey.identityFields.map(f=><label key={f}>{f}<input value={identity[f]||""} onChange={e=>setIdentity({...identity,[f]:e.target.value})}/></label>)}</div></section>}{questions.map((q,i)=><section className="public-question" key={q.id}><h2><b>{i+1}.</b> {q.title}{q.isRequired&&<em>*</em>}</h2>{q.description&&<p>{q.description}</p>}{q.type==="single"&&q.options.map(o=><label key={o.id}><input type="radio" name={q.id} checked={answers.find(a=>a.questionId===q.id)?.optionIds?.[0]===o.id} onChange={()=>setAnswer(q.id,{optionIds:[o.id]})}/>{o.label}</label>)}{q.type==="multiple"&&<>{q.options.map(o=>{const selected=answers.find(a=>a.questionId===q.id)?.optionIds||[];return <label key={o.id}><input type="checkbox" checked={selected.includes(o.id)} onChange={e=>setAnswer(q.id,{optionIds:e.target.checked?[...selected,o.id]:selected.filter(v=>v!==o.id)})}/>{o.label}</label>})}<small>{q.minSelections&&`최소 ${q.minSelections}개 `}{q.maxSelections&&`최대 ${q.maxSelections}개`}</small></>}{q.type==="short"&&<input className="public-text" value={answers.find(a=>a.questionId===q.id)?.textValue||""} onChange={e=>setAnswer(q.id,{textValue:e.target.value})}/>} {q.type==="long"&&<textarea value={answers.find(a=>a.questionId===q.id)?.textValue||""} onChange={e=>setAnswer(q.id,{textValue:e.target.value})}/>} {q.type==="scale5"&&<div className="scale-row"><span>{q.scaleMinLabel}</span>{[1,2,3,4,5].map(v=><label key={v}><input type="radio" name={q.id} checked={answers.find(a=>a.questionId===q.id)?.scaleValue===v} onChange={()=>setAnswer(q.id,{scaleValue:v})}/><b>{v}</b></label>)}<span>{q.scaleMaxLabel}</span></div>}{fields[q.id]&&<div className="field-error">{fields[q.id]}</div>}</section>)}{error&&<div className="api-error"><AlertTriangle/>{error}</div>}<button className="primary-btn public-submit" disabled={busy} onClick={submit}>{busy?<><LoaderCircle className="spin"/>제출 중</>:"응답 제출"}</button><p className="public-foot">응답은 제출 완료 후에만 저장됩니다. 익명 설문은 브라우저 삭제나 다른 기기 사용까지 중복을 완벽하게 제한할 수 없습니다.</p></section></main>
}
