"use client";
import { useMemo,useState } from "react";
import { AlertCircle,Check,ClipboardList,Copy,Edit3,LoaderCircle,Plus,RefreshCw,ShieldAlert,Sparkles,Trash2,Users } from "lucide-react";
import { FieldError } from "./generator-result";
import { hasInsufficientEvidence,OBSERVATION_CATEGORIES,RESULT_TYPES,selectStudentMemos,sortMemosByDate,validateObservationMemo,type ObservationCategory,type ObservationMemo,type ObservationMemoErrors,type ObservationResult,type ObservationResultType } from "../lib/student-observation-organizer";

type Draft=Omit<ObservationMemo,"id">;const today=new Date().toISOString().slice(0,10);
const emptyDraft:Draft={studentIdentifier:"",date:today,category:"학습 태도",situation:"",memo:"",teacherSupport:"",subsequentChange:""};
const toLines=(v:string[])=>v.join("\n");const fromLines=(v:string)=>v.split("\n").map(x=>x.trim()).filter(Boolean);

export function StudentObservationOrganizer(){
 const [draft,setDraft]=useState<Draft>(emptyDraft);const [errors,setErrors]=useState<ObservationMemoErrors>({});const [memos,setMemos]=useState<ObservationMemo[]>([]);const [editingId,setEditingId]=useState<string|null>(null);
 const [studentFilter,setStudentFilter]=useState("전체");const [categoryFilter,setCategoryFilter]=useState("전체");const [newest,setNewest]=useState(true);const [selectedStudent,setSelectedStudent]=useState("");const [resultType,setResultType]=useState<ObservationResultType>("두 결과 모두 생성");
 const [result,setResult]=useState<ObservationResult|null>(null);const [loading,setLoading]=useState(false);const [apiError,setApiError]=useState("");const [copied,setCopied]=useState(false);const [confirm,setConfirm]=useState<{type:"one"|"student";value:string}|null>(null);
 const students=useMemo(()=>[...new Set(memos.map(m=>m.studentIdentifier))].sort(),[memos]);const selectedMemos=useMemo(()=>selectedStudent?selectStudentMemos(memos,selectedStudent):[],[memos,selectedStudent]);
 const visible=useMemo(()=>sortMemosByDate(memos.filter(m=>(studentFilter==="전체"||m.studentIdentifier===studentFilter)&&(categoryFilter==="전체"||m.category===categoryFilter)),newest),[memos,studentFilter,categoryFilter,newest]);
 const update=<K extends keyof Draft>(key:K,value:Draft[K])=>{setDraft(c=>({...c,[key]:value}));if(key==="studentIdentifier"||key==="date"||key==="memo")setErrors(c=>({...c,[key]:undefined}));};
 const saveMemo=()=>{const v=validateObservationMemo(draft);setErrors(v.errors);if(!v.data)return;if(editingId)setMemos(c=>c.map(m=>m.id===editingId?{...v.data!,id:m.id}:m));else setMemos(c=>[...c,{...v.data!,id:crypto.randomUUID()}]);if(!selectedStudent)setSelectedStudent(v.data.studentIdentifier);setDraft({...emptyDraft,studentIdentifier:v.data.studentIdentifier});setEditingId(null);};
 const edit=(m:ObservationMemo)=>{setDraft({studentIdentifier:m.studentIdentifier,date:m.date,category:m.category,situation:m.situation||"",memo:m.memo,teacherSupport:m.teacherSupport||"",subsequentChange:m.subsequentChange||""});setEditingId(m.id);setErrors({});window.scrollTo({top:0,behavior:"smooth"});};
 const removeConfirmed=()=>{if(!confirm)return;if(confirm.type==="one")setMemos(c=>c.filter(m=>m.id!==confirm.value));else{setMemos(c=>c.filter(m=>m.studentIdentifier!==confirm.value));if(selectedStudent===confirm.value){setSelectedStudent("");setResult(null);}}setConfirm(null);};
 const generate=async()=>{if(!selectedStudent||!selectedMemos.length)return;setLoading(true);setApiError("");setCopied(false);try{const response=await fetch("/api/student-observations/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({studentIdentifier:selectedStudent,resultType,memos:selectedMemos})});const payload=await response.json() as {result?:ObservationResult;error?:string};if(!response.ok||!payload.result)throw new Error(payload.error||"관찰 기록을 정리하지 못했습니다.");setResult(payload.result);}catch(error){setApiError(error instanceof Error?error.message:"관찰 기록을 정리하지 못했습니다. 잠시 후 다시 시도해 주세요.");}finally{setLoading(false);}};
 const record=(i:number,key:keyof ObservationResult["organizedRecords"][number],value:string)=>setResult(c=>{if(!c)return c;const organizedRecords=[...c.organizedRecords];organizedRecords[i]={...organizedRecords[i],[key]:value};return{...c,organizedRecords};});
 const copyAll=async()=>{if(!result)return;const out=[`학생 식별명: ${result.studentIdentifier}`,...result.organizedRecords.flatMap(r=>["",`${r.date} · ${r.category}`,r.situation&&`관찰 상황: ${r.situation}`,`관찰 내용: ${r.objectiveObservation}`,r.teacherSupport&&`교사의 지도 또는 지원: ${r.teacherSupport}`,r.subsequentChange&&`이후 변화나 결과: ${r.subsequentChange}`].filter(Boolean)),result.repeatedStrengths.length?"\n반복 확인된 강점\n"+result.repeatedStrengths.map(x=>`- ${x}`).join("\n"):"",result.growthPoints.length?"\n성장 관점\n"+result.growthPoints.map(x=>`- ${x}`).join("\n"):"",result.behaviorCharacteristicsDraft&&"\n행동특성 및 종합의견 초안\n"+result.behaviorCharacteristicsDraft,result.insufficientEvidenceNotice&&"\n"+result.insufficientEvidenceNotice].filter(Boolean).join("\n");try{await navigator.clipboard.writeText(out);setCopied(true);window.setTimeout(()=>setCopied(false),2000);}catch{setApiError("복사하지 못했습니다. 내용을 직접 선택해 복사해 주세요.");}};
 return <><div className="page-title message-page-title"><div><span className="eyebrow">STUDENT OBSERVATION ASSISTANT</span><h1>학생 관찰 메모 정리기</h1><p>교사가 기록한 사실을 학생별·시간순으로 정리하고 성장 중심의 초안을 만들어요.</p></div><span className="privacy-note"><Check size={15}/> 메모는 현재 화면에서만 보관</span></div>
 <div className="observation-privacy"><ShieldAlert size={22}/><div><b>학생 개인정보를 안전하게 보호해 주세요</b><p>학생의 민감한 개인정보, 건강정보, 가족정보는 입력하지 마세요. AI가 작성한 결과는 초안이므로 교사가 반드시 사실관계를 확인하고 수정해야 합니다.</p><small>학생 이름 대신 번호, 이니셜 또는 교사가 구분할 수 있는 별칭 사용을 권장합니다. 메모는 저장되지 않으며 새로고침하면 삭제됩니다.</small></div></div>
 <div className="observation-layout"><section className="form-panel message-form observation-form"><div className="panel-head"><div><span className="eyebrow">STEP 1</span><h3>{editingId?"관찰 메모 수정":"관찰 메모 입력"}</h3></div><span className="required">* 필수 항목</span></div>
 <div className="field-row"><label>학생 식별명 *<input value={draft.studentIdentifier} placeholder="예: 12번, K, 별칭" onChange={e=>update("studentIdentifier",e.target.value)}/><FieldError message={errors.studentIdentifier}/></label><label>관찰 날짜 *<input type="date" value={draft.date} onChange={e=>update("date",e.target.value)}/><FieldError message={errors.date}/></label></div>
 <label>관찰 영역<select value={draft.category} onChange={e=>update("category",e.target.value as ObservationCategory)}>{OBSERVATION_CATEGORIES.map(x=><option key={x}>{x}</option>)}</select></label>
 <label>관찰 상황 <span className="optional">선택</span><input value={draft.situation} placeholder="예: 모둠별 발표 준비 시간" onChange={e=>update("situation",e.target.value)}/></label>
 <label>관찰 메모 *<textarea value={draft.memo} placeholder="해석이나 평가보다 직접 확인한 행동과 말을 적어 주세요." onChange={e=>update("memo",e.target.value)}/><FieldError message={errors.memo}/></label>
 <label>교사의 지도 또는 지원 내용 <span className="optional">선택</span><textarea value={draft.teacherSupport} placeholder="예: 역할을 나누어 참여할 수 있도록 안내함" onChange={e=>update("teacherSupport",e.target.value)}/></label>
 <label>이후 변화나 결과 <span className="optional">선택</span><textarea value={draft.subsequentChange} placeholder="확인된 변화나 결과가 있을 때만 적어 주세요." onChange={e=>update("subsequentChange",e.target.value)}/></label>
 <div className="memo-form-actions">{editingId&&<button className="ghost-btn" onClick={()=>{setEditingId(null);setDraft(emptyDraft);setErrors({});}}>수정 취소</button>}<button className="primary-btn" onClick={saveMemo}><Plus size={16}/>{editingId?"수정 완료":"메모 추가"}</button></div></section>
 <section className="observation-workspace"><div className="memo-list-panel"><div className="panel-head"><div><span className="eyebrow"><Users size={13}/> 현재 화면의 메모</span><h3>관찰 메모 {memos.length}건</h3></div></div><div className="memo-filters"><select value={studentFilter} onChange={e=>setStudentFilter(e.target.value)}><option>전체</option>{students.map(x=><option key={x}>{x}</option>)}</select><select value={categoryFilter} onChange={e=>setCategoryFilter(e.target.value)}><option>전체</option>{OBSERVATION_CATEGORIES.map(x=><option key={x}>{x}</option>)}</select><button className="ghost-btn" onClick={()=>setNewest(x=>!x)}>{newest?"최신순":"날짜순"}</button></div>
 {visible.length?<div className="memo-list">{visible.map(m=><article key={m.id}><div><span className="subject-badge">{m.category}</span><b>{m.studentIdentifier}</b><time>{m.date}</time></div>{m.situation&&<small>{m.situation}</small>}<p>{m.memo}</p>{m.teacherSupport&&<small>지원: {m.teacherSupport}</small>}<div className="memo-actions"><button onClick={()=>edit(m)}><Edit3 size={14}/> 수정</button><button onClick={()=>setConfirm({type:"one",value:m.id})}><Trash2 size={14}/> 삭제</button></div></article>)}</div>:<div className="memo-empty"><ClipboardList size={25}/><b>아직 추가된 관찰 메모가 없어요</b><p>왼쪽 입력란에서 첫 메모를 추가해 주세요.</p></div>}</div>
 <section className="generate-panel"><div className="panel-head"><div><span className="eyebrow">STEP 2</span><h3>결과 생성 설정</h3></div></div><div className="field-row"><label>정리할 학생<select value={selectedStudent} onChange={e=>{setSelectedStudent(e.target.value);setResult(null);}}><option value="">학생 선택</option>{students.map(x=><option key={x}>{x}</option>)}</select></label><label>결과 유형<select value={resultType} onChange={e=>setResultType(e.target.value as ObservationResultType)}>{RESULT_TYPES.map(x=><option key={x}>{x}</option>)}</select></label></div>
 {selectedStudent&&<div className="selected-summary"><span>{selectedStudent}</span><b>{selectedMemos.length}건의 메모만 AI에 전달됩니다.</b><button onClick={()=>setConfirm({type:"student",value:selectedStudent})}>이 학생 메모 전체 삭제</button></div>}
 {!selectedMemos.length?<p className="generation-notice">정리할 학생과 관찰 메모를 먼저 준비해 주세요.</p>:hasInsufficientEvidence(selectedMemos)&&<p className="evidence-warning"><AlertCircle size={16}/> 관찰 자료가 충분하지 않아 학생의 전반적인 특성을 판단하기 어려울 수 있습니다. 현재 기록만으로도 정리할 수 있습니다.</p>}
 <button className="primary-btn generate-message" disabled={loading||!selectedMemos.length} onClick={generate}>{loading?<><LoaderCircle className="spin" size={17}/> 기록을 정리하고 있어요</>:<><Sparkles size={17}/> 관찰 기록 정리</>}</button></section>
 <section className="observation-result" aria-live="polite"><div className="panel-head"><div><span className="eyebrow"><ClipboardList size={13}/> 생성 결과</span><h3>학생 관찰 기록 초안</h3></div>{result&&<span className="result-ready"><Check size={13}/> 직접 수정 가능</span>}</div>{apiError&&<div className="api-error"><AlertCircle size={19}/><div><b>결과를 생성하지 못했어요</b><p>{apiError}</p><span>선택한 학생의 메모를 확인한 뒤 다시 생성해 주세요.</span></div></div>}
 {!result?<div className="message-empty observation-empty"><ClipboardList size={28}/><b>아직 생성된 결과가 없어요</b><p>학생을 선택하고 현재 기록으로 정리를 진행해 주세요.</p></div>:<div className="observation-document">{result.insufficientEvidenceNotice&&<p className="evidence-warning">{result.insufficientEvidenceNotice}</p>}{result.organizedRecords.length>0&&<ResultSection title="상담·관찰 기록">{result.organizedRecords.map((r,i)=><div className="organized-record" key={`${r.date}-${i}`}><div><input value={r.date} onChange={e=>record(i,"date",e.target.value)}/><input value={r.category} onChange={e=>record(i,"category",e.target.value)}/></div>{(["situation","objectiveObservation","teacherSupport","subsequentChange"] as const).map(k=><label key={k}><span>{{situation:"관찰 상황",objectiveObservation:"객관적으로 정리한 관찰 내용",teacherSupport:"교사의 지도 또는 지원",subsequentChange:"이후 변화나 결과"}[k]}</span><textarea value={r[k]} placeholder="입력된 내용 없음" onChange={e=>record(i,k,e.target.value)}/></label>)}</div>)}</ResultSection>}
 {result.repeatedStrengths.length>0&&<ResultSection title="반복 확인된 강점"><textarea value={toLines(result.repeatedStrengths)} onChange={e=>setResult(c=>c?{...c,repeatedStrengths:fromLines(e.target.value)}:c)}/></ResultSection>}{result.growthPoints.length>0&&<ResultSection title="성장 관점"><textarea value={toLines(result.growthPoints)} onChange={e=>setResult(c=>c?{...c,growthPoints:fromLines(e.target.value)}:c)}/></ResultSection>}{result.behaviorCharacteristicsDraft&&<ResultSection title="행동특성 및 종합의견 초안"><textarea className="draft-editor" value={result.behaviorCharacteristicsDraft} onChange={e=>setResult(c=>c?{...c,behaviorCharacteristicsDraft:e.target.value}:c)}/></ResultSection>}
 <p className="edit-hint">공식 기록에 자동 반영되지 않습니다. 교사가 원문 메모와 사실관계를 반드시 확인해 주세요.</p><div className="preview-actions message-actions"><button className="ghost-btn" onClick={copyAll}>{copied?<><Check size={16}/> 복사 완료</>:<><Copy size={16}/> 전체 내용 복사</>}</button><button className="primary-btn" onClick={generate} disabled={loading}><RefreshCw size={16}/> 다시 생성</button></div></div>}</section></section></div>
 {confirm&&<div className="confirm-backdrop" role="presentation"><div className="confirm-dialog" role="dialog" aria-modal="true" aria-labelledby="delete-title"><span><Trash2 size={20}/></span><h3 id="delete-title">메모를 삭제할까요?</h3><p>{confirm.type==="student"?`${confirm.value} 학생의 메모를 모두 삭제합니다.`:"선택한 메모를 삭제합니다."} 삭제한 내용은 복구할 수 없습니다.</p><div><button className="ghost-btn" onClick={()=>setConfirm(null)}>취소</button><button className="danger-btn" onClick={removeConfirmed}>삭제</button></div></div></div>}</>;
}
function ResultSection({title,children}:{title:string;children:React.ReactNode}){return <section className="observation-result-section"><h4>{title}</h4>{children}</section>}
