import test from "node:test";import assert from "node:assert/strict";
const lib=await import("../app/lib/role-assignment.ts");
const students=[1,2,3,4].map(n=>({id:`s${n}`,classId:"c1",studentNumber:n,displayName:`학생${n}`,isActive:true}));
const roles=[{id:"r1",classId:"c1",name:"칠판",description:"",capacity:2,displayOrder:0,isActive:true},{id:"r2",classId:"c1",name:"정리",description:"",capacity:2,displayOrder:1,isActive:true}];
test("assigns every active student once without exceeding capacity",()=>{const result=lib.allocateRoles({students,roles,preferences:[],history:[],random:lib.seededRandom(3)});assert.equal(result.ok,true);assert.equal(new Set(result.assignments.map(a=>a.studentId)).size,4);assert.equal(result.assignments.filter(a=>a.roleId==="r1").length,2);});
test("keeps fixed assignments and respects exclusions",()=>{const preferences=[{studentId:"s1",excludedRoleIds:[],note:"",lockedRoleId:"r1"},{studentId:"s2",excludedRoleIds:["r1"],note:""}];const result=lib.allocateRoles({students,roles,preferences,history:[],random:lib.seededRandom(4)});assert.equal(result.ok,true);assert.equal(result.assignments.find(a=>a.studentId==="s1").roleId,"r1");assert.equal(result.assignments.find(a=>a.studentId==="s2").roleId,"r2");});
test("blocks capacity mismatch and impossible exclusions",()=>{assert.equal(lib.allocateRoles({students,roles:[{...roles[0],capacity:1},roles[1]],preferences:[],history:[]}).ok,false);const preferences=students.map(s=>({studentId:s.id,excludedRoleIds:["r2"],note:""}));assert.equal(lib.allocateRoles({students,roles,preferences,history:[],random:lib.seededRandom(1)}).ok,false);});
test("prefers choices and recent-role alternatives when possible",()=>{const preferences=students.map((s,i)=>({studentId:s.id,firstChoiceRoleId:i<2?"r1":"r2",excludedRoleIds:[],note:""}));const history=[{studentId:"s1",roleId:"r1",cycleStartDate:"2026-01-01"}];const result=lib.allocateRoles({students,roles,preferences,history,random:lib.seededRandom(2)});assert.equal(result.ok,true);assert.equal(result.assignments.find(a=>a.studentId==="s2").roleId,"r1");});
test("validates swaps, duplicate choices and inactive students",()=>{assert.equal(lib.duplicateChoices({studentId:"s1",firstChoiceRoleId:"r1",secondChoiceRoleId:"r1",excludedRoleIds:[],note:""}),true);assert.equal(lib.canSwap({studentId:"s1",roleId:"r1",isLocked:false,assignmentSource:"auto"},{studentId:"s2",roleId:"r2",isLocked:false,assignmentSource:"auto"},[{studentId:"s1",excludedRoleIds:["r2"],note:""}]),false);});
