import { getChatGPTUser } from "../../chatgpt-auth";
import { createObservationMemo,deleteObservationMemo,deleteStudentObservationMemos,listObservationMemos,ObservationStoreError,updateObservationMemo } from "../../lib/observation-store";
import { validateObservationMemo } from "../../lib/student-observation-organizer";

const unauthorized=()=>Response.json({error:"로그인 후 관찰 메모를 이용해 주세요."},{status:401});
const failure=(error:unknown)=>Response.json({error:error instanceof ObservationStoreError?error.message:"관찰 메모를 처리하지 못했습니다."},{status:500});
const uuid=(value:unknown)=>typeof value==="string"&&/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value);

export async function GET(){const user=await getChatGPTUser();if(!user)return unauthorized();try{return Response.json({memos:await listObservationMemos(user.email)});}catch(error){return failure(error);}}
export async function POST(request:Request){const user=await getChatGPTUser();if(!user)return unauthorized();let payload:unknown;try{payload=await request.json();}catch{return Response.json({error:"입력 내용을 확인해 주세요."},{status:400});}const validation=validateObservationMemo(payload);if(!validation.data)return Response.json({error:"필수 입력값을 확인해 주세요.",fields:validation.errors},{status:400});try{return Response.json({memo:await createObservationMemo(user.email,validation.data)},{status:201});}catch(error){return failure(error);}}
export async function PATCH(request:Request){const user=await getChatGPTUser();if(!user)return unauthorized();let payload:unknown;try{payload=await request.json();}catch{return Response.json({error:"입력 내용을 확인해 주세요."},{status:400});}if(!payload||typeof payload!=="object"||!uuid((payload as Record<string,unknown>).id))return Response.json({error:"수정할 메모를 확인해 주세요."},{status:400});const validation=validateObservationMemo(payload);if(!validation.data)return Response.json({error:"필수 입력값을 확인해 주세요.",fields:validation.errors},{status:400});try{return Response.json({memo:await updateObservationMemo(user.email,(payload as {id:string}).id,validation.data)});}catch(error){return failure(error);}}
export async function DELETE(request:Request){const user=await getChatGPTUser();if(!user)return unauthorized();let payload:unknown;try{payload=await request.json();}catch{return Response.json({error:"삭제할 메모를 확인해 주세요."},{status:400});}if(!payload||typeof payload!=="object")return Response.json({error:"삭제할 메모를 확인해 주세요."},{status:400});const raw=payload as Record<string,unknown>;try{if(uuid(raw.id))await deleteObservationMemo(user.email,raw.id as string);else if(typeof raw.studentIdentifier==="string"&&raw.studentIdentifier.trim())await deleteStudentObservationMemos(user.email,raw.studentIdentifier.trim());else return Response.json({error:"삭제할 메모를 확인해 주세요."},{status:400});return new Response(null,{status:204});}catch(error){return failure(error);}}
